/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables;


import io.corbs.baseballdb.schema.Baseballdb;
import io.corbs.baseballdb.schema.tables.records.AwardsmanagersRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Awardsmanagers extends TableImpl<AwardsmanagersRecord> {

    private static final long serialVersionUID = -571621171;

    /**
     * The reference instance of <code>baseballdb.AwardsManagers</code>
     */
    public static final Awardsmanagers AWARDSMANAGERS = new Awardsmanagers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AwardsmanagersRecord> getRecordType() {
        return AwardsmanagersRecord.class;
    }

    /**
     * The column <code>baseballdb.AwardsManagers.playerID</code>.
     */
    public final TableField<AwardsmanagersRecord, String> PLAYERID = createField("playerID", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.AwardsManagers.awardID</code>.
     */
    public final TableField<AwardsmanagersRecord, String> AWARDID = createField("awardID", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.AwardsManagers.yearID</code>.
     */
    public final TableField<AwardsmanagersRecord, Integer> YEARID = createField("yearID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.AwardsManagers.lgID</code>.
     */
    public final TableField<AwardsmanagersRecord, String> LGID = createField("lgID", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.AwardsManagers.tie</code>.
     */
    public final TableField<AwardsmanagersRecord, String> TIE = createField("tie", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.AwardsManagers.notes</code>.
     */
    public final TableField<AwardsmanagersRecord, String> NOTES = createField("notes", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * Create a <code>baseballdb.AwardsManagers</code> table reference
     */
    public Awardsmanagers() {
        this("AwardsManagers", null);
    }

    /**
     * Create an aliased <code>baseballdb.AwardsManagers</code> table reference
     */
    public Awardsmanagers(String alias) {
        this(alias, AWARDSMANAGERS);
    }

    private Awardsmanagers(String alias, Table<AwardsmanagersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Awardsmanagers(String alias, Table<AwardsmanagersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Baseballdb.BASEBALLDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Awardsmanagers as(String alias) {
        return new Awardsmanagers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Awardsmanagers rename(String name) {
        return new Awardsmanagers(name, null);
    }
}
