/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables;


import io.corbs.baseballdb.schema.Baseballdb;
import io.corbs.baseballdb.schema.tables.records.CollegeplayingRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Collegeplaying extends TableImpl<CollegeplayingRecord> {

    private static final long serialVersionUID = -692986599;

    /**
     * The reference instance of <code>baseballdb.CollegePlaying</code>
     */
    public static final Collegeplaying COLLEGEPLAYING = new Collegeplaying();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CollegeplayingRecord> getRecordType() {
        return CollegeplayingRecord.class;
    }

    /**
     * The column <code>baseballdb.CollegePlaying.playerID</code>.
     */
    public final TableField<CollegeplayingRecord, String> PLAYERID = createField("playerID", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.CollegePlaying.schoolID</code>.
     */
    public final TableField<CollegeplayingRecord, String> SCHOOLID = createField("schoolID", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.CollegePlaying.yearID</code>.
     */
    public final TableField<CollegeplayingRecord, Integer> YEARID = createField("yearID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>baseballdb.CollegePlaying</code> table reference
     */
    public Collegeplaying() {
        this("CollegePlaying", null);
    }

    /**
     * Create an aliased <code>baseballdb.CollegePlaying</code> table reference
     */
    public Collegeplaying(String alias) {
        this(alias, COLLEGEPLAYING);
    }

    private Collegeplaying(String alias, Table<CollegeplayingRecord> aliased) {
        this(alias, aliased, null);
    }

    private Collegeplaying(String alias, Table<CollegeplayingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Baseballdb.BASEBALLDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Collegeplaying as(String alias) {
        return new Collegeplaying(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Collegeplaying rename(String name) {
        return new Collegeplaying(name, null);
    }
}
