/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables;


import io.corbs.baseballdb.schema.Baseballdb;
import io.corbs.baseballdb.schema.tables.records.FieldingofsplitRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fieldingofsplit extends TableImpl<FieldingofsplitRecord> {

    private static final long serialVersionUID = -1259241917;

    /**
     * The reference instance of <code>baseballdb.FieldingOFsplit</code>
     */
    public static final Fieldingofsplit FIELDINGOFSPLIT = new Fieldingofsplit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FieldingofsplitRecord> getRecordType() {
        return FieldingofsplitRecord.class;
    }

    /**
     * The column <code>baseballdb.FieldingOFsplit.playerID</code>.
     */
    public final TableField<FieldingofsplitRecord, String> PLAYERID = createField("playerID", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.FieldingOFsplit.yearID</code>.
     */
    public final TableField<FieldingofsplitRecord, Integer> YEARID = createField("yearID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.FieldingOFsplit.stint</code>.
     */
    public final TableField<FieldingofsplitRecord, Integer> STINT = createField("stint", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.FieldingOFsplit.teamID</code>.
     */
    public final TableField<FieldingofsplitRecord, String> TEAMID = createField("teamID", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.FieldingOFsplit.lgID</code>.
     */
    public final TableField<FieldingofsplitRecord, String> LGID = createField("lgID", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.FieldingOFsplit.POS</code>.
     */
    public final TableField<FieldingofsplitRecord, String> POS = createField("POS", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.FieldingOFsplit.G</code>.
     */
    public final TableField<FieldingofsplitRecord, Integer> G = createField("G", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.FieldingOFsplit.GS</code>.
     */
    public final TableField<FieldingofsplitRecord, Integer> GS = createField("GS", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.FieldingOFsplit.InnOuts</code>.
     */
    public final TableField<FieldingofsplitRecord, Integer> INNOUTS = createField("InnOuts", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.FieldingOFsplit.PO</code>.
     */
    public final TableField<FieldingofsplitRecord, Integer> PO = createField("PO", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.FieldingOFsplit.A</code>.
     */
    public final TableField<FieldingofsplitRecord, Integer> A = createField("A", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.FieldingOFsplit.E</code>.
     */
    public final TableField<FieldingofsplitRecord, Integer> E = createField("E", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.FieldingOFsplit.DP</code>.
     */
    public final TableField<FieldingofsplitRecord, Integer> DP = createField("DP", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.FieldingOFsplit.PB</code>.
     */
    public final TableField<FieldingofsplitRecord, String> PB = createField("PB", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.FieldingOFsplit.WP</code>.
     */
    public final TableField<FieldingofsplitRecord, String> WP = createField("WP", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.FieldingOFsplit.SB</code>.
     */
    public final TableField<FieldingofsplitRecord, String> SB = createField("SB", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.FieldingOFsplit.CS</code>.
     */
    public final TableField<FieldingofsplitRecord, String> CS = createField("CS", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.FieldingOFsplit.ZR</code>.
     */
    public final TableField<FieldingofsplitRecord, String> ZR = createField("ZR", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * Create a <code>baseballdb.FieldingOFsplit</code> table reference
     */
    public Fieldingofsplit() {
        this("FieldingOFsplit", null);
    }

    /**
     * Create an aliased <code>baseballdb.FieldingOFsplit</code> table reference
     */
    public Fieldingofsplit(String alias) {
        this(alias, FIELDINGOFSPLIT);
    }

    private Fieldingofsplit(String alias, Table<FieldingofsplitRecord> aliased) {
        this(alias, aliased, null);
    }

    private Fieldingofsplit(String alias, Table<FieldingofsplitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Baseballdb.BASEBALLDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Fieldingofsplit as(String alias) {
        return new Fieldingofsplit(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Fieldingofsplit rename(String name) {
        return new Fieldingofsplit(name, null);
    }
}
