/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables;


import io.corbs.baseballdb.schema.Baseballdb;
import io.corbs.baseballdb.schema.tables.records.ManagershalfRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Managershalf extends TableImpl<ManagershalfRecord> {

    private static final long serialVersionUID = -313900122;

    /**
     * The reference instance of <code>baseballdb.ManagersHalf</code>
     */
    public static final Managershalf MANAGERSHALF = new Managershalf();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ManagershalfRecord> getRecordType() {
        return ManagershalfRecord.class;
    }

    /**
     * The column <code>baseballdb.ManagersHalf.playerID</code>.
     */
    public final TableField<ManagershalfRecord, String> PLAYERID = createField("playerID", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.ManagersHalf.yearID</code>.
     */
    public final TableField<ManagershalfRecord, Integer> YEARID = createField("yearID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.ManagersHalf.teamID</code>.
     */
    public final TableField<ManagershalfRecord, String> TEAMID = createField("teamID", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.ManagersHalf.lgID</code>.
     */
    public final TableField<ManagershalfRecord, String> LGID = createField("lgID", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.ManagersHalf.inseason</code>.
     */
    public final TableField<ManagershalfRecord, Integer> INSEASON = createField("inseason", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.ManagersHalf.half</code>.
     */
    public final TableField<ManagershalfRecord, Integer> HALF = createField("half", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.ManagersHalf.G</code>.
     */
    public final TableField<ManagershalfRecord, Integer> G = createField("G", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.ManagersHalf.W</code>.
     */
    public final TableField<ManagershalfRecord, Integer> W = createField("W", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.ManagersHalf.L</code>.
     */
    public final TableField<ManagershalfRecord, Integer> L = createField("L", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.ManagersHalf.rank</code>.
     */
    public final TableField<ManagershalfRecord, Integer> RANK = createField("rank", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>baseballdb.ManagersHalf</code> table reference
     */
    public Managershalf() {
        this("ManagersHalf", null);
    }

    /**
     * Create an aliased <code>baseballdb.ManagersHalf</code> table reference
     */
    public Managershalf(String alias) {
        this(alias, MANAGERSHALF);
    }

    private Managershalf(String alias, Table<ManagershalfRecord> aliased) {
        this(alias, aliased, null);
    }

    private Managershalf(String alias, Table<ManagershalfRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Baseballdb.BASEBALLDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Managershalf as(String alias) {
        return new Managershalf(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Managershalf rename(String name) {
        return new Managershalf(name, null);
    }
}
