/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables;


import io.corbs.baseballdb.schema.Baseballdb;
import io.corbs.baseballdb.schema.tables.records.MasterRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Master extends TableImpl<MasterRecord> {

    private static final long serialVersionUID = 2000986573;

    /**
     * The reference instance of <code>baseballdb.Master</code>
     */
    public static final Master MASTER = new Master();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MasterRecord> getRecordType() {
        return MasterRecord.class;
    }

    /**
     * The column <code>baseballdb.Master.playerID</code>.
     */
    public final TableField<MasterRecord, String> PLAYERID = createField("playerID", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Master.birthYear</code>.
     */
    public final TableField<MasterRecord, Integer> BIRTHYEAR = createField("birthYear", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.Master.birthMonth</code>.
     */
    public final TableField<MasterRecord, Integer> BIRTHMONTH = createField("birthMonth", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.Master.birthDay</code>.
     */
    public final TableField<MasterRecord, Integer> BIRTHDAY = createField("birthDay", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.Master.birthCountry</code>.
     */
    public final TableField<MasterRecord, String> BIRTHCOUNTRY = createField("birthCountry", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Master.birthState</code>.
     */
    public final TableField<MasterRecord, String> BIRTHSTATE = createField("birthState", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Master.birthCity</code>.
     */
    public final TableField<MasterRecord, String> BIRTHCITY = createField("birthCity", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Master.deathYear</code>.
     */
    public final TableField<MasterRecord, String> DEATHYEAR = createField("deathYear", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Master.deathMonth</code>.
     */
    public final TableField<MasterRecord, String> DEATHMONTH = createField("deathMonth", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Master.deathDay</code>.
     */
    public final TableField<MasterRecord, String> DEATHDAY = createField("deathDay", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Master.deathCountry</code>.
     */
    public final TableField<MasterRecord, String> DEATHCOUNTRY = createField("deathCountry", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Master.deathState</code>.
     */
    public final TableField<MasterRecord, String> DEATHSTATE = createField("deathState", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Master.deathCity</code>.
     */
    public final TableField<MasterRecord, String> DEATHCITY = createField("deathCity", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Master.nameFirst</code>.
     */
    public final TableField<MasterRecord, String> NAMEFIRST = createField("nameFirst", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Master.nameLast</code>.
     */
    public final TableField<MasterRecord, String> NAMELAST = createField("nameLast", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Master.nameGiven</code>.
     */
    public final TableField<MasterRecord, String> NAMEGIVEN = createField("nameGiven", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Master.weight</code>.
     */
    public final TableField<MasterRecord, Integer> WEIGHT = createField("weight", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.Master.height</code>.
     */
    public final TableField<MasterRecord, Integer> HEIGHT = createField("height", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>baseballdb.Master.bats</code>.
     */
    public final TableField<MasterRecord, String> BATS = createField("bats", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Master.throws</code>.
     */
    public final TableField<MasterRecord, String> THROWS = createField("throws", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Master.debut</code>.
     */
    public final TableField<MasterRecord, String> DEBUT = createField("debut", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Master.finalGame</code>.
     */
    public final TableField<MasterRecord, String> FINALGAME = createField("finalGame", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Master.retroID</code>.
     */
    public final TableField<MasterRecord, String> RETROID = createField("retroID", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Master.bbrefID</code>.
     */
    public final TableField<MasterRecord, String> BBREFID = createField("bbrefID", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * Create a <code>baseballdb.Master</code> table reference
     */
    public Master() {
        this("Master", null);
    }

    /**
     * Create an aliased <code>baseballdb.Master</code> table reference
     */
    public Master(String alias) {
        this(alias, MASTER);
    }

    private Master(String alias, Table<MasterRecord> aliased) {
        this(alias, aliased, null);
    }

    private Master(String alias, Table<MasterRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Baseballdb.BASEBALLDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Master as(String alias) {
        return new Master(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Master rename(String name) {
        return new Master(name, null);
    }
}
