/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables;


import io.corbs.baseballdb.schema.Baseballdb;
import io.corbs.baseballdb.schema.tables.records.ParksRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Parks extends TableImpl<ParksRecord> {

    private static final long serialVersionUID = 772212817;

    /**
     * The reference instance of <code>baseballdb.Parks</code>
     */
    public static final Parks PARKS = new Parks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ParksRecord> getRecordType() {
        return ParksRecord.class;
    }

    /**
     * The column <code>baseballdb.Parks.park.key</code>.
     */
    public final TableField<ParksRecord, String> PARK_KEY = createField("park.key", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Parks.park.name</code>.
     */
    public final TableField<ParksRecord, String> PARK_NAME = createField("park.name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Parks.park.alias</code>.
     */
    public final TableField<ParksRecord, String> PARK_ALIAS = createField("park.alias", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Parks.city</code>.
     */
    public final TableField<ParksRecord, String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Parks.state</code>.
     */
    public final TableField<ParksRecord, String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Parks.country</code>.
     */
    public final TableField<ParksRecord, String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * Create a <code>baseballdb.Parks</code> table reference
     */
    public Parks() {
        this("Parks", null);
    }

    /**
     * Create an aliased <code>baseballdb.Parks</code> table reference
     */
    public Parks(String alias) {
        this(alias, PARKS);
    }

    private Parks(String alias, Table<ParksRecord> aliased) {
        this(alias, aliased, null);
    }

    private Parks(String alias, Table<ParksRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Baseballdb.BASEBALLDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Parks as(String alias) {
        return new Parks(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Parks rename(String name) {
        return new Parks(name, null);
    }
}
