/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables;


import io.corbs.baseballdb.schema.Baseballdb;
import io.corbs.baseballdb.schema.tables.records.SchoolsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Schools extends TableImpl<SchoolsRecord> {

    private static final long serialVersionUID = -1389773535;

    /**
     * The reference instance of <code>baseballdb.Schools</code>
     */
    public static final Schools SCHOOLS = new Schools();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SchoolsRecord> getRecordType() {
        return SchoolsRecord.class;
    }

    /**
     * The column <code>baseballdb.Schools.schoolID</code>.
     */
    public final TableField<SchoolsRecord, String> SCHOOLID = createField("schoolID", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Schools.name_full</code>.
     */
    public final TableField<SchoolsRecord, String> NAME_FULL = createField("name_full", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Schools.city</code>.
     */
    public final TableField<SchoolsRecord, String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Schools.state</code>.
     */
    public final TableField<SchoolsRecord, String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>baseballdb.Schools.country</code>.
     */
    public final TableField<SchoolsRecord, String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * Create a <code>baseballdb.Schools</code> table reference
     */
    public Schools() {
        this("Schools", null);
    }

    /**
     * Create an aliased <code>baseballdb.Schools</code> table reference
     */
    public Schools(String alias) {
        this(alias, SCHOOLS);
    }

    private Schools(String alias, Table<SchoolsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Schools(String alias, Table<SchoolsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Baseballdb.BASEBALLDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schools as(String alias) {
        return new Schools(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Schools rename(String name) {
        return new Schools(name, null);
    }
}
