/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAwardsshareplayers extends Serializable {

    /**
     * Setter for <code>baseballdb.AwardsSharePlayers.awardID</code>.
     */
    public IAwardsshareplayers setAwardid(String value);

    /**
     * Getter for <code>baseballdb.AwardsSharePlayers.awardID</code>.
     */
    public String getAwardid();

    /**
     * Setter for <code>baseballdb.AwardsSharePlayers.yearID</code>.
     */
    public IAwardsshareplayers setYearid(Integer value);

    /**
     * Getter for <code>baseballdb.AwardsSharePlayers.yearID</code>.
     */
    public Integer getYearid();

    /**
     * Setter for <code>baseballdb.AwardsSharePlayers.lgID</code>.
     */
    public IAwardsshareplayers setLgid(String value);

    /**
     * Getter for <code>baseballdb.AwardsSharePlayers.lgID</code>.
     */
    public String getLgid();

    /**
     * Setter for <code>baseballdb.AwardsSharePlayers.playerID</code>.
     */
    public IAwardsshareplayers setPlayerid(String value);

    /**
     * Getter for <code>baseballdb.AwardsSharePlayers.playerID</code>.
     */
    public String getPlayerid();

    /**
     * Setter for <code>baseballdb.AwardsSharePlayers.pointsWon</code>.
     */
    public IAwardsshareplayers setPointswon(Integer value);

    /**
     * Getter for <code>baseballdb.AwardsSharePlayers.pointsWon</code>.
     */
    public Integer getPointswon();

    /**
     * Setter for <code>baseballdb.AwardsSharePlayers.pointsMax</code>.
     */
    public IAwardsshareplayers setPointsmax(Integer value);

    /**
     * Getter for <code>baseballdb.AwardsSharePlayers.pointsMax</code>.
     */
    public Integer getPointsmax();

    /**
     * Setter for <code>baseballdb.AwardsSharePlayers.votesFirst</code>.
     */
    public IAwardsshareplayers setVotesfirst(Integer value);

    /**
     * Getter for <code>baseballdb.AwardsSharePlayers.votesFirst</code>.
     */
    public Integer getVotesfirst();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IAwardsshareplayers
     */
    public void from(io.corbs.baseballdb.schema.tables.interfaces.IAwardsshareplayers from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IAwardsshareplayers
     */
    public <E extends io.corbs.baseballdb.schema.tables.interfaces.IAwardsshareplayers> E into(E into);
}
