/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAwardsmanagers extends Serializable {

    /**
     * Setter for <code>baseballdb.AwardsManagers.playerID</code>.
     */
    public IAwardsmanagers setPlayerid(String value);

    /**
     * Getter for <code>baseballdb.AwardsManagers.playerID</code>.
     */
    public String getPlayerid();

    /**
     * Setter for <code>baseballdb.AwardsManagers.awardID</code>.
     */
    public IAwardsmanagers setAwardid(String value);

    /**
     * Getter for <code>baseballdb.AwardsManagers.awardID</code>.
     */
    public String getAwardid();

    /**
     * Setter for <code>baseballdb.AwardsManagers.yearID</code>.
     */
    public IAwardsmanagers setYearid(Integer value);

    /**
     * Getter for <code>baseballdb.AwardsManagers.yearID</code>.
     */
    public Integer getYearid();

    /**
     * Setter for <code>baseballdb.AwardsManagers.lgID</code>.
     */
    public IAwardsmanagers setLgid(String value);

    /**
     * Getter for <code>baseballdb.AwardsManagers.lgID</code>.
     */
    public String getLgid();

    /**
     * Setter for <code>baseballdb.AwardsManagers.tie</code>.
     */
    public IAwardsmanagers setTie(String value);

    /**
     * Getter for <code>baseballdb.AwardsManagers.tie</code>.
     */
    public String getTie();

    /**
     * Setter for <code>baseballdb.AwardsManagers.notes</code>.
     */
    public IAwardsmanagers setNotes(String value);

    /**
     * Getter for <code>baseballdb.AwardsManagers.notes</code>.
     */
    public String getNotes();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IAwardsmanagers
     */
    public void from(io.corbs.baseballdb.schema.tables.interfaces.IAwardsmanagers from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IAwardsmanagers
     */
    public <E extends io.corbs.baseballdb.schema.tables.interfaces.IAwardsmanagers> E into(E into);
}
