/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IFieldingof extends Serializable {

    /**
     * Setter for <code>baseballdb.FieldingOF.playerID</code>.
     */
    public IFieldingof setPlayerid(String value);

    /**
     * Getter for <code>baseballdb.FieldingOF.playerID</code>.
     */
    public String getPlayerid();

    /**
     * Setter for <code>baseballdb.FieldingOF.yearID</code>.
     */
    public IFieldingof setYearid(Integer value);

    /**
     * Getter for <code>baseballdb.FieldingOF.yearID</code>.
     */
    public Integer getYearid();

    /**
     * Setter for <code>baseballdb.FieldingOF.stint</code>.
     */
    public IFieldingof setStint(Integer value);

    /**
     * Getter for <code>baseballdb.FieldingOF.stint</code>.
     */
    public Integer getStint();

    /**
     * Setter for <code>baseballdb.FieldingOF.Glf</code>.
     */
    public IFieldingof setGlf(Integer value);

    /**
     * Getter for <code>baseballdb.FieldingOF.Glf</code>.
     */
    public Integer getGlf();

    /**
     * Setter for <code>baseballdb.FieldingOF.Gcf</code>.
     */
    public IFieldingof setGcf(Integer value);

    /**
     * Getter for <code>baseballdb.FieldingOF.Gcf</code>.
     */
    public Integer getGcf();

    /**
     * Setter for <code>baseballdb.FieldingOF.Grf</code>.
     */
    public IFieldingof setGrf(Integer value);

    /**
     * Getter for <code>baseballdb.FieldingOF.Grf</code>.
     */
    public Integer getGrf();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IFieldingof
     */
    public void from(io.corbs.baseballdb.schema.tables.interfaces.IFieldingof from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IFieldingof
     */
    public <E extends io.corbs.baseballdb.schema.tables.interfaces.IFieldingof> E into(E into);
}
