/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IFieldingpost extends Serializable {

    /**
     * Setter for <code>baseballdb.FieldingPost.playerID</code>.
     */
    public IFieldingpost setPlayerid(String value);

    /**
     * Getter for <code>baseballdb.FieldingPost.playerID</code>.
     */
    public String getPlayerid();

    /**
     * Setter for <code>baseballdb.FieldingPost.yearID</code>.
     */
    public IFieldingpost setYearid(Integer value);

    /**
     * Getter for <code>baseballdb.FieldingPost.yearID</code>.
     */
    public Integer getYearid();

    /**
     * Setter for <code>baseballdb.FieldingPost.teamID</code>.
     */
    public IFieldingpost setTeamid(String value);

    /**
     * Getter for <code>baseballdb.FieldingPost.teamID</code>.
     */
    public String getTeamid();

    /**
     * Setter for <code>baseballdb.FieldingPost.lgID</code>.
     */
    public IFieldingpost setLgid(String value);

    /**
     * Getter for <code>baseballdb.FieldingPost.lgID</code>.
     */
    public String getLgid();

    /**
     * Setter for <code>baseballdb.FieldingPost.round</code>.
     */
    public IFieldingpost setRound(String value);

    /**
     * Getter for <code>baseballdb.FieldingPost.round</code>.
     */
    public String getRound();

    /**
     * Setter for <code>baseballdb.FieldingPost.POS</code>.
     */
    public IFieldingpost setPos(String value);

    /**
     * Getter for <code>baseballdb.FieldingPost.POS</code>.
     */
    public String getPos();

    /**
     * Setter for <code>baseballdb.FieldingPost.G</code>.
     */
    public IFieldingpost setG(Integer value);

    /**
     * Getter for <code>baseballdb.FieldingPost.G</code>.
     */
    public Integer getG();

    /**
     * Setter for <code>baseballdb.FieldingPost.GS</code>.
     */
    public IFieldingpost setGs(Integer value);

    /**
     * Getter for <code>baseballdb.FieldingPost.GS</code>.
     */
    public Integer getGs();

    /**
     * Setter for <code>baseballdb.FieldingPost.InnOuts</code>.
     */
    public IFieldingpost setInnouts(Integer value);

    /**
     * Getter for <code>baseballdb.FieldingPost.InnOuts</code>.
     */
    public Integer getInnouts();

    /**
     * Setter for <code>baseballdb.FieldingPost.PO</code>.
     */
    public IFieldingpost setPo(Integer value);

    /**
     * Getter for <code>baseballdb.FieldingPost.PO</code>.
     */
    public Integer getPo();

    /**
     * Setter for <code>baseballdb.FieldingPost.A</code>.
     */
    public IFieldingpost setA(Integer value);

    /**
     * Getter for <code>baseballdb.FieldingPost.A</code>.
     */
    public Integer getA();

    /**
     * Setter for <code>baseballdb.FieldingPost.E</code>.
     */
    public IFieldingpost setE(Integer value);

    /**
     * Getter for <code>baseballdb.FieldingPost.E</code>.
     */
    public Integer getE();

    /**
     * Setter for <code>baseballdb.FieldingPost.DP</code>.
     */
    public IFieldingpost setDp(Integer value);

    /**
     * Getter for <code>baseballdb.FieldingPost.DP</code>.
     */
    public Integer getDp();

    /**
     * Setter for <code>baseballdb.FieldingPost.TP</code>.
     */
    public IFieldingpost setTp(Integer value);

    /**
     * Getter for <code>baseballdb.FieldingPost.TP</code>.
     */
    public Integer getTp();

    /**
     * Setter for <code>baseballdb.FieldingPost.PB</code>.
     */
    public IFieldingpost setPb(String value);

    /**
     * Getter for <code>baseballdb.FieldingPost.PB</code>.
     */
    public String getPb();

    /**
     * Setter for <code>baseballdb.FieldingPost.SB</code>.
     */
    public IFieldingpost setSb(String value);

    /**
     * Getter for <code>baseballdb.FieldingPost.SB</code>.
     */
    public String getSb();

    /**
     * Setter for <code>baseballdb.FieldingPost.CS</code>.
     */
    public IFieldingpost setCs(String value);

    /**
     * Getter for <code>baseballdb.FieldingPost.CS</code>.
     */
    public String getCs();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IFieldingpost
     */
    public void from(io.corbs.baseballdb.schema.tables.interfaces.IFieldingpost from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IFieldingpost
     */
    public <E extends io.corbs.baseballdb.schema.tables.interfaces.IFieldingpost> E into(E into);
}
