/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IManagershalf extends Serializable {

    /**
     * Setter for <code>baseballdb.ManagersHalf.playerID</code>.
     */
    public IManagershalf setPlayerid(String value);

    /**
     * Getter for <code>baseballdb.ManagersHalf.playerID</code>.
     */
    public String getPlayerid();

    /**
     * Setter for <code>baseballdb.ManagersHalf.yearID</code>.
     */
    public IManagershalf setYearid(Integer value);

    /**
     * Getter for <code>baseballdb.ManagersHalf.yearID</code>.
     */
    public Integer getYearid();

    /**
     * Setter for <code>baseballdb.ManagersHalf.teamID</code>.
     */
    public IManagershalf setTeamid(String value);

    /**
     * Getter for <code>baseballdb.ManagersHalf.teamID</code>.
     */
    public String getTeamid();

    /**
     * Setter for <code>baseballdb.ManagersHalf.lgID</code>.
     */
    public IManagershalf setLgid(String value);

    /**
     * Getter for <code>baseballdb.ManagersHalf.lgID</code>.
     */
    public String getLgid();

    /**
     * Setter for <code>baseballdb.ManagersHalf.inseason</code>.
     */
    public IManagershalf setInseason(Integer value);

    /**
     * Getter for <code>baseballdb.ManagersHalf.inseason</code>.
     */
    public Integer getInseason();

    /**
     * Setter for <code>baseballdb.ManagersHalf.half</code>.
     */
    public IManagershalf setHalf(Integer value);

    /**
     * Getter for <code>baseballdb.ManagersHalf.half</code>.
     */
    public Integer getHalf();

    /**
     * Setter for <code>baseballdb.ManagersHalf.G</code>.
     */
    public IManagershalf setG(Integer value);

    /**
     * Getter for <code>baseballdb.ManagersHalf.G</code>.
     */
    public Integer getG();

    /**
     * Setter for <code>baseballdb.ManagersHalf.W</code>.
     */
    public IManagershalf setW(Integer value);

    /**
     * Getter for <code>baseballdb.ManagersHalf.W</code>.
     */
    public Integer getW();

    /**
     * Setter for <code>baseballdb.ManagersHalf.L</code>.
     */
    public IManagershalf setL(Integer value);

    /**
     * Getter for <code>baseballdb.ManagersHalf.L</code>.
     */
    public Integer getL();

    /**
     * Setter for <code>baseballdb.ManagersHalf.rank</code>.
     */
    public IManagershalf setRank(Integer value);

    /**
     * Getter for <code>baseballdb.ManagersHalf.rank</code>.
     */
    public Integer getRank();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IManagershalf
     */
    public void from(io.corbs.baseballdb.schema.tables.interfaces.IManagershalf from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IManagershalf
     */
    public <E extends io.corbs.baseballdb.schema.tables.interfaces.IManagershalf> E into(E into);
}
