/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IMaster extends Serializable {

    /**
     * Setter for <code>baseballdb.Master.playerID</code>.
     */
    public IMaster setPlayerid(String value);

    /**
     * Getter for <code>baseballdb.Master.playerID</code>.
     */
    public String getPlayerid();

    /**
     * Setter for <code>baseballdb.Master.birthYear</code>.
     */
    public IMaster setBirthyear(Integer value);

    /**
     * Getter for <code>baseballdb.Master.birthYear</code>.
     */
    public Integer getBirthyear();

    /**
     * Setter for <code>baseballdb.Master.birthMonth</code>.
     */
    public IMaster setBirthmonth(Integer value);

    /**
     * Getter for <code>baseballdb.Master.birthMonth</code>.
     */
    public Integer getBirthmonth();

    /**
     * Setter for <code>baseballdb.Master.birthDay</code>.
     */
    public IMaster setBirthday(Integer value);

    /**
     * Getter for <code>baseballdb.Master.birthDay</code>.
     */
    public Integer getBirthday();

    /**
     * Setter for <code>baseballdb.Master.birthCountry</code>.
     */
    public IMaster setBirthcountry(String value);

    /**
     * Getter for <code>baseballdb.Master.birthCountry</code>.
     */
    public String getBirthcountry();

    /**
     * Setter for <code>baseballdb.Master.birthState</code>.
     */
    public IMaster setBirthstate(String value);

    /**
     * Getter for <code>baseballdb.Master.birthState</code>.
     */
    public String getBirthstate();

    /**
     * Setter for <code>baseballdb.Master.birthCity</code>.
     */
    public IMaster setBirthcity(String value);

    /**
     * Getter for <code>baseballdb.Master.birthCity</code>.
     */
    public String getBirthcity();

    /**
     * Setter for <code>baseballdb.Master.deathYear</code>.
     */
    public IMaster setDeathyear(String value);

    /**
     * Getter for <code>baseballdb.Master.deathYear</code>.
     */
    public String getDeathyear();

    /**
     * Setter for <code>baseballdb.Master.deathMonth</code>.
     */
    public IMaster setDeathmonth(String value);

    /**
     * Getter for <code>baseballdb.Master.deathMonth</code>.
     */
    public String getDeathmonth();

    /**
     * Setter for <code>baseballdb.Master.deathDay</code>.
     */
    public IMaster setDeathday(String value);

    /**
     * Getter for <code>baseballdb.Master.deathDay</code>.
     */
    public String getDeathday();

    /**
     * Setter for <code>baseballdb.Master.deathCountry</code>.
     */
    public IMaster setDeathcountry(String value);

    /**
     * Getter for <code>baseballdb.Master.deathCountry</code>.
     */
    public String getDeathcountry();

    /**
     * Setter for <code>baseballdb.Master.deathState</code>.
     */
    public IMaster setDeathstate(String value);

    /**
     * Getter for <code>baseballdb.Master.deathState</code>.
     */
    public String getDeathstate();

    /**
     * Setter for <code>baseballdb.Master.deathCity</code>.
     */
    public IMaster setDeathcity(String value);

    /**
     * Getter for <code>baseballdb.Master.deathCity</code>.
     */
    public String getDeathcity();

    /**
     * Setter for <code>baseballdb.Master.nameFirst</code>.
     */
    public IMaster setNamefirst(String value);

    /**
     * Getter for <code>baseballdb.Master.nameFirst</code>.
     */
    public String getNamefirst();

    /**
     * Setter for <code>baseballdb.Master.nameLast</code>.
     */
    public IMaster setNamelast(String value);

    /**
     * Getter for <code>baseballdb.Master.nameLast</code>.
     */
    public String getNamelast();

    /**
     * Setter for <code>baseballdb.Master.nameGiven</code>.
     */
    public IMaster setNamegiven(String value);

    /**
     * Getter for <code>baseballdb.Master.nameGiven</code>.
     */
    public String getNamegiven();

    /**
     * Setter for <code>baseballdb.Master.weight</code>.
     */
    public IMaster setWeight(Integer value);

    /**
     * Getter for <code>baseballdb.Master.weight</code>.
     */
    public Integer getWeight();

    /**
     * Setter for <code>baseballdb.Master.height</code>.
     */
    public IMaster setHeight(Integer value);

    /**
     * Getter for <code>baseballdb.Master.height</code>.
     */
    public Integer getHeight();

    /**
     * Setter for <code>baseballdb.Master.bats</code>.
     */
    public IMaster setBats(String value);

    /**
     * Getter for <code>baseballdb.Master.bats</code>.
     */
    public String getBats();

    /**
     * Setter for <code>baseballdb.Master.throws</code>.
     */
    public IMaster setThrows(String value);

    /**
     * Getter for <code>baseballdb.Master.throws</code>.
     */
    public String getThrows();

    /**
     * Setter for <code>baseballdb.Master.debut</code>.
     */
    public IMaster setDebut(String value);

    /**
     * Getter for <code>baseballdb.Master.debut</code>.
     */
    public String getDebut();

    /**
     * Setter for <code>baseballdb.Master.finalGame</code>.
     */
    public IMaster setFinalgame(String value);

    /**
     * Getter for <code>baseballdb.Master.finalGame</code>.
     */
    public String getFinalgame();

    /**
     * Setter for <code>baseballdb.Master.retroID</code>.
     */
    public IMaster setRetroid(String value);

    /**
     * Getter for <code>baseballdb.Master.retroID</code>.
     */
    public String getRetroid();

    /**
     * Setter for <code>baseballdb.Master.bbrefID</code>.
     */
    public IMaster setBbrefid(String value);

    /**
     * Getter for <code>baseballdb.Master.bbrefID</code>.
     */
    public String getBbrefid();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IMaster
     */
    public void from(io.corbs.baseballdb.schema.tables.interfaces.IMaster from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IMaster
     */
    public <E extends io.corbs.baseballdb.schema.tables.interfaces.IMaster> E into(E into);
}
