/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISalaries extends Serializable {

    /**
     * Setter for <code>baseballdb.Salaries.yearID</code>.
     */
    public ISalaries setYearid(Integer value);

    /**
     * Getter for <code>baseballdb.Salaries.yearID</code>.
     */
    public Integer getYearid();

    /**
     * Setter for <code>baseballdb.Salaries.teamID</code>.
     */
    public ISalaries setTeamid(String value);

    /**
     * Getter for <code>baseballdb.Salaries.teamID</code>.
     */
    public String getTeamid();

    /**
     * Setter for <code>baseballdb.Salaries.lgID</code>.
     */
    public ISalaries setLgid(String value);

    /**
     * Getter for <code>baseballdb.Salaries.lgID</code>.
     */
    public String getLgid();

    /**
     * Setter for <code>baseballdb.Salaries.playerID</code>.
     */
    public ISalaries setPlayerid(String value);

    /**
     * Getter for <code>baseballdb.Salaries.playerID</code>.
     */
    public String getPlayerid();

    /**
     * Setter for <code>baseballdb.Salaries.salary</code>.
     */
    public ISalaries setSalary(Integer value);

    /**
     * Getter for <code>baseballdb.Salaries.salary</code>.
     */
    public Integer getSalary();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISalaries
     */
    public void from(io.corbs.baseballdb.schema.tables.interfaces.ISalaries from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISalaries
     */
    public <E extends io.corbs.baseballdb.schema.tables.interfaces.ISalaries> E into(E into);
}
