/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISchools extends Serializable {

    /**
     * Setter for <code>baseballdb.Schools.schoolID</code>.
     */
    public ISchools setSchoolid(String value);

    /**
     * Getter for <code>baseballdb.Schools.schoolID</code>.
     */
    public String getSchoolid();

    /**
     * Setter for <code>baseballdb.Schools.name_full</code>.
     */
    public ISchools setNameFull(String value);

    /**
     * Getter for <code>baseballdb.Schools.name_full</code>.
     */
    public String getNameFull();

    /**
     * Setter for <code>baseballdb.Schools.city</code>.
     */
    public ISchools setCity(String value);

    /**
     * Getter for <code>baseballdb.Schools.city</code>.
     */
    public String getCity();

    /**
     * Setter for <code>baseballdb.Schools.state</code>.
     */
    public ISchools setState(String value);

    /**
     * Getter for <code>baseballdb.Schools.state</code>.
     */
    public String getState();

    /**
     * Setter for <code>baseballdb.Schools.country</code>.
     */
    public ISchools setCountry(String value);

    /**
     * Getter for <code>baseballdb.Schools.country</code>.
     */
    public String getCountry();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISchools
     */
    public void from(io.corbs.baseballdb.schema.tables.interfaces.ISchools from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISchools
     */
    public <E extends io.corbs.baseballdb.schema.tables.interfaces.ISchools> E into(E into);
}
