/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITeams extends Serializable {

    /**
     * Setter for <code>baseballdb.Teams.yearID</code>.
     */
    public ITeams setYearid(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.yearID</code>.
     */
    public Integer getYearid();

    /**
     * Setter for <code>baseballdb.Teams.lgID</code>.
     */
    public ITeams setLgid(String value);

    /**
     * Getter for <code>baseballdb.Teams.lgID</code>.
     */
    public String getLgid();

    /**
     * Setter for <code>baseballdb.Teams.teamID</code>.
     */
    public ITeams setTeamid(String value);

    /**
     * Getter for <code>baseballdb.Teams.teamID</code>.
     */
    public String getTeamid();

    /**
     * Setter for <code>baseballdb.Teams.franchID</code>.
     */
    public ITeams setFranchid(String value);

    /**
     * Getter for <code>baseballdb.Teams.franchID</code>.
     */
    public String getFranchid();

    /**
     * Setter for <code>baseballdb.Teams.divID</code>.
     */
    public ITeams setDivid(String value);

    /**
     * Getter for <code>baseballdb.Teams.divID</code>.
     */
    public String getDivid();

    /**
     * Setter for <code>baseballdb.Teams.Rank</code>.
     */
    public ITeams setRank(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.Rank</code>.
     */
    public Integer getRank();

    /**
     * Setter for <code>baseballdb.Teams.G</code>.
     */
    public ITeams setG(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.G</code>.
     */
    public Integer getG();

    /**
     * Setter for <code>baseballdb.Teams.Ghome</code>.
     */
    public ITeams setGhome(String value);

    /**
     * Getter for <code>baseballdb.Teams.Ghome</code>.
     */
    public String getGhome();

    /**
     * Setter for <code>baseballdb.Teams.W</code>.
     */
    public ITeams setW(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.W</code>.
     */
    public Integer getW();

    /**
     * Setter for <code>baseballdb.Teams.L</code>.
     */
    public ITeams setL(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.L</code>.
     */
    public Integer getL();

    /**
     * Setter for <code>baseballdb.Teams.DivWin</code>.
     */
    public ITeams setDivwin(String value);

    /**
     * Getter for <code>baseballdb.Teams.DivWin</code>.
     */
    public String getDivwin();

    /**
     * Setter for <code>baseballdb.Teams.WCWin</code>.
     */
    public ITeams setWcwin(String value);

    /**
     * Getter for <code>baseballdb.Teams.WCWin</code>.
     */
    public String getWcwin();

    /**
     * Setter for <code>baseballdb.Teams.LgWin</code>.
     */
    public ITeams setLgwin(String value);

    /**
     * Getter for <code>baseballdb.Teams.LgWin</code>.
     */
    public String getLgwin();

    /**
     * Setter for <code>baseballdb.Teams.WSWin</code>.
     */
    public ITeams setWswin(String value);

    /**
     * Getter for <code>baseballdb.Teams.WSWin</code>.
     */
    public String getWswin();

    /**
     * Setter for <code>baseballdb.Teams.R</code>.
     */
    public ITeams setR(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.R</code>.
     */
    public Integer getR();

    /**
     * Setter for <code>baseballdb.Teams.AB</code>.
     */
    public ITeams setAb(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.AB</code>.
     */
    public Integer getAb();

    /**
     * Setter for <code>baseballdb.Teams.H</code>.
     */
    public ITeams setH(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.H</code>.
     */
    public Integer getH();

    /**
     * Setter for <code>baseballdb.Teams.2B</code>.
     */
    public ITeams set_2b(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.2B</code>.
     */
    public Integer get_2b();

    /**
     * Setter for <code>baseballdb.Teams.3B</code>.
     */
    public ITeams set_3b(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.3B</code>.
     */
    public Integer get_3b();

    /**
     * Setter for <code>baseballdb.Teams.HR</code>.
     */
    public ITeams setHr(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.HR</code>.
     */
    public Integer getHr();

    /**
     * Setter for <code>baseballdb.Teams.BB</code>.
     */
    public ITeams setBb(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.BB</code>.
     */
    public Integer getBb();

    /**
     * Setter for <code>baseballdb.Teams.SO</code>.
     */
    public ITeams setSo(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.SO</code>.
     */
    public Integer getSo();

    /**
     * Setter for <code>baseballdb.Teams.SB</code>.
     */
    public ITeams setSb(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.SB</code>.
     */
    public Integer getSb();

    /**
     * Setter for <code>baseballdb.Teams.CS</code>.
     */
    public ITeams setCs(String value);

    /**
     * Getter for <code>baseballdb.Teams.CS</code>.
     */
    public String getCs();

    /**
     * Setter for <code>baseballdb.Teams.HBP</code>.
     */
    public ITeams setHbp(String value);

    /**
     * Getter for <code>baseballdb.Teams.HBP</code>.
     */
    public String getHbp();

    /**
     * Setter for <code>baseballdb.Teams.SF</code>.
     */
    public ITeams setSf(String value);

    /**
     * Getter for <code>baseballdb.Teams.SF</code>.
     */
    public String getSf();

    /**
     * Setter for <code>baseballdb.Teams.RA</code>.
     */
    public ITeams setRa(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.RA</code>.
     */
    public Integer getRa();

    /**
     * Setter for <code>baseballdb.Teams.ER</code>.
     */
    public ITeams setEr(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.ER</code>.
     */
    public Integer getEr();

    /**
     * Setter for <code>baseballdb.Teams.ERA</code>.
     */
    public ITeams setEra(Double value);

    /**
     * Getter for <code>baseballdb.Teams.ERA</code>.
     */
    public Double getEra();

    /**
     * Setter for <code>baseballdb.Teams.CG</code>.
     */
    public ITeams setCg(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.CG</code>.
     */
    public Integer getCg();

    /**
     * Setter for <code>baseballdb.Teams.SHO</code>.
     */
    public ITeams setSho(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.SHO</code>.
     */
    public Integer getSho();

    /**
     * Setter for <code>baseballdb.Teams.SV</code>.
     */
    public ITeams setSv(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.SV</code>.
     */
    public Integer getSv();

    /**
     * Setter for <code>baseballdb.Teams.IPouts</code>.
     */
    public ITeams setIpouts(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.IPouts</code>.
     */
    public Integer getIpouts();

    /**
     * Setter for <code>baseballdb.Teams.HA</code>.
     */
    public ITeams setHa(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.HA</code>.
     */
    public Integer getHa();

    /**
     * Setter for <code>baseballdb.Teams.HRA</code>.
     */
    public ITeams setHra(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.HRA</code>.
     */
    public Integer getHra();

    /**
     * Setter for <code>baseballdb.Teams.BBA</code>.
     */
    public ITeams setBba(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.BBA</code>.
     */
    public Integer getBba();

    /**
     * Setter for <code>baseballdb.Teams.SOA</code>.
     */
    public ITeams setSoa(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.SOA</code>.
     */
    public Integer getSoa();

    /**
     * Setter for <code>baseballdb.Teams.E</code>.
     */
    public ITeams setE(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.E</code>.
     */
    public Integer getE();

    /**
     * Setter for <code>baseballdb.Teams.DP</code>.
     */
    public ITeams setDp(String value);

    /**
     * Getter for <code>baseballdb.Teams.DP</code>.
     */
    public String getDp();

    /**
     * Setter for <code>baseballdb.Teams.FP</code>.
     */
    public ITeams setFp(Double value);

    /**
     * Getter for <code>baseballdb.Teams.FP</code>.
     */
    public Double getFp();

    /**
     * Setter for <code>baseballdb.Teams.name</code>.
     */
    public ITeams setName(String value);

    /**
     * Getter for <code>baseballdb.Teams.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>baseballdb.Teams.park</code>.
     */
    public ITeams setPark(String value);

    /**
     * Getter for <code>baseballdb.Teams.park</code>.
     */
    public String getPark();

    /**
     * Setter for <code>baseballdb.Teams.attendance</code>.
     */
    public ITeams setAttendance(String value);

    /**
     * Getter for <code>baseballdb.Teams.attendance</code>.
     */
    public String getAttendance();

    /**
     * Setter for <code>baseballdb.Teams.BPF</code>.
     */
    public ITeams setBpf(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.BPF</code>.
     */
    public Integer getBpf();

    /**
     * Setter for <code>baseballdb.Teams.PPF</code>.
     */
    public ITeams setPpf(Integer value);

    /**
     * Getter for <code>baseballdb.Teams.PPF</code>.
     */
    public Integer getPpf();

    /**
     * Setter for <code>baseballdb.Teams.teamIDBR</code>.
     */
    public ITeams setTeamidbr(String value);

    /**
     * Getter for <code>baseballdb.Teams.teamIDBR</code>.
     */
    public String getTeamidbr();

    /**
     * Setter for <code>baseballdb.Teams.teamIDlahman45</code>.
     */
    public ITeams setTeamidlahman45(String value);

    /**
     * Getter for <code>baseballdb.Teams.teamIDlahman45</code>.
     */
    public String getTeamidlahman45();

    /**
     * Setter for <code>baseballdb.Teams.teamIDretro</code>.
     */
    public ITeams setTeamidretro(String value);

    /**
     * Getter for <code>baseballdb.Teams.teamIDretro</code>.
     */
    public String getTeamidretro();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITeams
     */
    public void from(io.corbs.baseballdb.schema.tables.interfaces.ITeams from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITeams
     */
    public <E extends io.corbs.baseballdb.schema.tables.interfaces.ITeams> E into(E into);
}
