/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.records;


import io.corbs.baseballdb.schema.tables.Awardssharemanagers;
import io.corbs.baseballdb.schema.tables.interfaces.IAwardssharemanagers;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AwardssharemanagersRecord extends TableRecordImpl<AwardssharemanagersRecord> implements Record7<String, Integer, String, String, Integer, Integer, Integer>, IAwardssharemanagers {

    private static final long serialVersionUID = 1883309257;

    /**
     * Setter for <code>baseballdb.AwardsShareManagers.awardID</code>.
     */
    @Override
    public AwardssharemanagersRecord setAwardid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.AwardsShareManagers.awardID</code>.
     */
    @Override
    public String getAwardid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>baseballdb.AwardsShareManagers.yearID</code>.
     */
    @Override
    public AwardssharemanagersRecord setYearid(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.AwardsShareManagers.yearID</code>.
     */
    @Override
    public Integer getYearid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>baseballdb.AwardsShareManagers.lgID</code>.
     */
    @Override
    public AwardssharemanagersRecord setLgid(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.AwardsShareManagers.lgID</code>.
     */
    @Override
    public String getLgid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>baseballdb.AwardsShareManagers.playerID</code>.
     */
    @Override
    public AwardssharemanagersRecord setPlayerid(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.AwardsShareManagers.playerID</code>.
     */
    @Override
    public String getPlayerid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>baseballdb.AwardsShareManagers.pointsWon</code>.
     */
    @Override
    public AwardssharemanagersRecord setPointswon(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.AwardsShareManagers.pointsWon</code>.
     */
    @Override
    public Integer getPointswon() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>baseballdb.AwardsShareManagers.pointsMax</code>.
     */
    @Override
    public AwardssharemanagersRecord setPointsmax(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.AwardsShareManagers.pointsMax</code>.
     */
    @Override
    public Integer getPointsmax() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>baseballdb.AwardsShareManagers.votesFirst</code>.
     */
    @Override
    public AwardssharemanagersRecord setVotesfirst(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.AwardsShareManagers.votesFirst</code>.
     */
    @Override
    public Integer getVotesfirst() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, Integer, String, String, Integer, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, Integer, String, String, Integer, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Awardssharemanagers.AWARDSSHAREMANAGERS.AWARDID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Awardssharemanagers.AWARDSSHAREMANAGERS.YEARID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Awardssharemanagers.AWARDSSHAREMANAGERS.LGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Awardssharemanagers.AWARDSSHAREMANAGERS.PLAYERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Awardssharemanagers.AWARDSSHAREMANAGERS.POINTSWON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Awardssharemanagers.AWARDSSHAREMANAGERS.POINTSMAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Awardssharemanagers.AWARDSSHAREMANAGERS.VOTESFIRST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getAwardid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getYearid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLgid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPlayerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getPointswon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getPointsmax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getVotesfirst();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AwardssharemanagersRecord value1(String value) {
        setAwardid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AwardssharemanagersRecord value2(Integer value) {
        setYearid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AwardssharemanagersRecord value3(String value) {
        setLgid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AwardssharemanagersRecord value4(String value) {
        setPlayerid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AwardssharemanagersRecord value5(Integer value) {
        setPointswon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AwardssharemanagersRecord value6(Integer value) {
        setPointsmax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AwardssharemanagersRecord value7(Integer value) {
        setVotesfirst(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AwardssharemanagersRecord values(String value1, Integer value2, String value3, String value4, Integer value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IAwardssharemanagers from) {
        setAwardid(from.getAwardid());
        setYearid(from.getYearid());
        setLgid(from.getLgid());
        setPlayerid(from.getPlayerid());
        setPointswon(from.getPointswon());
        setPointsmax(from.getPointsmax());
        setVotesfirst(from.getVotesfirst());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IAwardssharemanagers> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AwardssharemanagersRecord
     */
    public AwardssharemanagersRecord() {
        super(Awardssharemanagers.AWARDSSHAREMANAGERS);
    }

    /**
     * Create a detached, initialised AwardssharemanagersRecord
     */
    public AwardssharemanagersRecord(String awardid, Integer yearid, String lgid, String playerid, Integer pointswon, Integer pointsmax, Integer votesfirst) {
        super(Awardssharemanagers.AWARDSSHAREMANAGERS);

        set(0, awardid);
        set(1, yearid);
        set(2, lgid);
        set(3, playerid);
        set(4, pointswon);
        set(5, pointsmax);
        set(6, votesfirst);
    }
}
