/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.records;


import io.corbs.baseballdb.schema.tables.Halloffame;
import io.corbs.baseballdb.schema.tables.interfaces.IHalloffame;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HalloffameRecord extends TableRecordImpl<HalloffameRecord> implements Record9<String, Integer, String, Integer, Integer, Integer, String, String, String>, IHalloffame {

    private static final long serialVersionUID = -189149617;

    /**
     * Setter for <code>baseballdb.HallOfFame.playerID</code>.
     */
    @Override
    public HalloffameRecord setPlayerid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.HallOfFame.playerID</code>.
     */
    @Override
    public String getPlayerid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>baseballdb.HallOfFame.yearid</code>.
     */
    @Override
    public HalloffameRecord setYearid(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.HallOfFame.yearid</code>.
     */
    @Override
    public Integer getYearid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>baseballdb.HallOfFame.votedBy</code>.
     */
    @Override
    public HalloffameRecord setVotedby(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.HallOfFame.votedBy</code>.
     */
    @Override
    public String getVotedby() {
        return (String) get(2);
    }

    /**
     * Setter for <code>baseballdb.HallOfFame.ballots</code>.
     */
    @Override
    public HalloffameRecord setBallots(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.HallOfFame.ballots</code>.
     */
    @Override
    public Integer getBallots() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>baseballdb.HallOfFame.needed</code>.
     */
    @Override
    public HalloffameRecord setNeeded(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.HallOfFame.needed</code>.
     */
    @Override
    public Integer getNeeded() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>baseballdb.HallOfFame.votes</code>.
     */
    @Override
    public HalloffameRecord setVotes(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.HallOfFame.votes</code>.
     */
    @Override
    public Integer getVotes() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>baseballdb.HallOfFame.inducted</code>.
     */
    @Override
    public HalloffameRecord setInducted(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.HallOfFame.inducted</code>.
     */
    @Override
    public String getInducted() {
        return (String) get(6);
    }

    /**
     * Setter for <code>baseballdb.HallOfFame.category</code>.
     */
    @Override
    public HalloffameRecord setCategory(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.HallOfFame.category</code>.
     */
    @Override
    public String getCategory() {
        return (String) get(7);
    }

    /**
     * Setter for <code>baseballdb.HallOfFame.needed_note</code>.
     */
    @Override
    public HalloffameRecord setNeededNote(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.HallOfFame.needed_note</code>.
     */
    @Override
    public String getNeededNote() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, Integer, String, Integer, Integer, Integer, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, Integer, String, Integer, Integer, Integer, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Halloffame.HALLOFFAME.PLAYERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Halloffame.HALLOFFAME.YEARID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Halloffame.HALLOFFAME.VOTEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Halloffame.HALLOFFAME.BALLOTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Halloffame.HALLOFFAME.NEEDED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Halloffame.HALLOFFAME.VOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Halloffame.HALLOFFAME.INDUCTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Halloffame.HALLOFFAME.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Halloffame.HALLOFFAME.NEEDED_NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPlayerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getYearid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getVotedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getBallots();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getNeeded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getVotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getInducted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getNeededNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HalloffameRecord value1(String value) {
        setPlayerid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HalloffameRecord value2(Integer value) {
        setYearid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HalloffameRecord value3(String value) {
        setVotedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HalloffameRecord value4(Integer value) {
        setBallots(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HalloffameRecord value5(Integer value) {
        setNeeded(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HalloffameRecord value6(Integer value) {
        setVotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HalloffameRecord value7(String value) {
        setInducted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HalloffameRecord value8(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HalloffameRecord value9(String value) {
        setNeededNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HalloffameRecord values(String value1, Integer value2, String value3, Integer value4, Integer value5, Integer value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IHalloffame from) {
        setPlayerid(from.getPlayerid());
        setYearid(from.getYearid());
        setVotedby(from.getVotedby());
        setBallots(from.getBallots());
        setNeeded(from.getNeeded());
        setVotes(from.getVotes());
        setInducted(from.getInducted());
        setCategory(from.getCategory());
        setNeededNote(from.getNeededNote());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IHalloffame> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HalloffameRecord
     */
    public HalloffameRecord() {
        super(Halloffame.HALLOFFAME);
    }

    /**
     * Create a detached, initialised HalloffameRecord
     */
    public HalloffameRecord(String playerid, Integer yearid, String votedby, Integer ballots, Integer needed, Integer votes, String inducted, String category, String neededNote) {
        super(Halloffame.HALLOFFAME);

        set(0, playerid);
        set(1, yearid);
        set(2, votedby);
        set(3, ballots);
        set(4, needed);
        set(5, votes);
        set(6, inducted);
        set(7, category);
        set(8, neededNote);
    }
}
