/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.records;


import io.corbs.baseballdb.schema.tables.Managershalf;
import io.corbs.baseballdb.schema.tables.interfaces.IManagershalf;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ManagershalfRecord extends TableRecordImpl<ManagershalfRecord> implements Record10<String, Integer, String, String, Integer, Integer, Integer, Integer, Integer, Integer>, IManagershalf {

    private static final long serialVersionUID = -1940091816;

    /**
     * Setter for <code>baseballdb.ManagersHalf.playerID</code>.
     */
    @Override
    public ManagershalfRecord setPlayerid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.ManagersHalf.playerID</code>.
     */
    @Override
    public String getPlayerid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>baseballdb.ManagersHalf.yearID</code>.
     */
    @Override
    public ManagershalfRecord setYearid(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.ManagersHalf.yearID</code>.
     */
    @Override
    public Integer getYearid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>baseballdb.ManagersHalf.teamID</code>.
     */
    @Override
    public ManagershalfRecord setTeamid(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.ManagersHalf.teamID</code>.
     */
    @Override
    public String getTeamid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>baseballdb.ManagersHalf.lgID</code>.
     */
    @Override
    public ManagershalfRecord setLgid(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.ManagersHalf.lgID</code>.
     */
    @Override
    public String getLgid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>baseballdb.ManagersHalf.inseason</code>.
     */
    @Override
    public ManagershalfRecord setInseason(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.ManagersHalf.inseason</code>.
     */
    @Override
    public Integer getInseason() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>baseballdb.ManagersHalf.half</code>.
     */
    @Override
    public ManagershalfRecord setHalf(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.ManagersHalf.half</code>.
     */
    @Override
    public Integer getHalf() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>baseballdb.ManagersHalf.G</code>.
     */
    @Override
    public ManagershalfRecord setG(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.ManagersHalf.G</code>.
     */
    @Override
    public Integer getG() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>baseballdb.ManagersHalf.W</code>.
     */
    @Override
    public ManagershalfRecord setW(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.ManagersHalf.W</code>.
     */
    @Override
    public Integer getW() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>baseballdb.ManagersHalf.L</code>.
     */
    @Override
    public ManagershalfRecord setL(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.ManagersHalf.L</code>.
     */
    @Override
    public Integer getL() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>baseballdb.ManagersHalf.rank</code>.
     */
    @Override
    public ManagershalfRecord setRank(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.ManagersHalf.rank</code>.
     */
    @Override
    public Integer getRank() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, Integer, String, String, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, Integer, String, String, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Managershalf.MANAGERSHALF.PLAYERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Managershalf.MANAGERSHALF.YEARID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Managershalf.MANAGERSHALF.TEAMID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Managershalf.MANAGERSHALF.LGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Managershalf.MANAGERSHALF.INSEASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Managershalf.MANAGERSHALF.HALF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Managershalf.MANAGERSHALF.G;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Managershalf.MANAGERSHALF.W;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Managershalf.MANAGERSHALF.L;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Managershalf.MANAGERSHALF.RANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPlayerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getYearid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTeamid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLgid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getInseason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getHalf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getG();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getW();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getL();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagershalfRecord value1(String value) {
        setPlayerid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagershalfRecord value2(Integer value) {
        setYearid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagershalfRecord value3(String value) {
        setTeamid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagershalfRecord value4(String value) {
        setLgid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagershalfRecord value5(Integer value) {
        setInseason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagershalfRecord value6(Integer value) {
        setHalf(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagershalfRecord value7(Integer value) {
        setG(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagershalfRecord value8(Integer value) {
        setW(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagershalfRecord value9(Integer value) {
        setL(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagershalfRecord value10(Integer value) {
        setRank(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManagershalfRecord values(String value1, Integer value2, String value3, String value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IManagershalf from) {
        setPlayerid(from.getPlayerid());
        setYearid(from.getYearid());
        setTeamid(from.getTeamid());
        setLgid(from.getLgid());
        setInseason(from.getInseason());
        setHalf(from.getHalf());
        setG(from.getG());
        setW(from.getW());
        setL(from.getL());
        setRank(from.getRank());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IManagershalf> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ManagershalfRecord
     */
    public ManagershalfRecord() {
        super(Managershalf.MANAGERSHALF);
    }

    /**
     * Create a detached, initialised ManagershalfRecord
     */
    public ManagershalfRecord(String playerid, Integer yearid, String teamid, String lgid, Integer inseason, Integer half, Integer g, Integer w, Integer l, Integer rank) {
        super(Managershalf.MANAGERSHALF);

        set(0, playerid);
        set(1, yearid);
        set(2, teamid);
        set(3, lgid);
        set(4, inseason);
        set(5, half);
        set(6, g);
        set(7, w);
        set(8, l);
        set(9, rank);
    }
}
