/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.records;


import io.corbs.baseballdb.schema.tables.Teamsfranchises;
import io.corbs.baseballdb.schema.tables.interfaces.ITeamsfranchises;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamsfranchisesRecord extends TableRecordImpl<TeamsfranchisesRecord> implements Record4<String, String, String, String>, ITeamsfranchises {

    private static final long serialVersionUID = -701141547;

    /**
     * Setter for <code>baseballdb.TeamsFranchises.franchID</code>.
     */
    @Override
    public TeamsfranchisesRecord setFranchid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.TeamsFranchises.franchID</code>.
     */
    @Override
    public String getFranchid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>baseballdb.TeamsFranchises.franchName</code>.
     */
    @Override
    public TeamsfranchisesRecord setFranchname(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.TeamsFranchises.franchName</code>.
     */
    @Override
    public String getFranchname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>baseballdb.TeamsFranchises.active</code>.
     */
    @Override
    public TeamsfranchisesRecord setActive(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.TeamsFranchises.active</code>.
     */
    @Override
    public String getActive() {
        return (String) get(2);
    }

    /**
     * Setter for <code>baseballdb.TeamsFranchises.NAassoc</code>.
     */
    @Override
    public TeamsfranchisesRecord setNaassoc(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.TeamsFranchises.NAassoc</code>.
     */
    @Override
    public String getNaassoc() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Teamsfranchises.TEAMSFRANCHISES.FRANCHID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Teamsfranchises.TEAMSFRANCHISES.FRANCHNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Teamsfranchises.TEAMSFRANCHISES.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Teamsfranchises.TEAMSFRANCHISES.NAASSOC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getFranchid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFranchname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getNaassoc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeamsfranchisesRecord value1(String value) {
        setFranchid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeamsfranchisesRecord value2(String value) {
        setFranchname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeamsfranchisesRecord value3(String value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeamsfranchisesRecord value4(String value) {
        setNaassoc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeamsfranchisesRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITeamsfranchises from) {
        setFranchid(from.getFranchid());
        setFranchname(from.getFranchname());
        setActive(from.getActive());
        setNaassoc(from.getNaassoc());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITeamsfranchises> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamsfranchisesRecord
     */
    public TeamsfranchisesRecord() {
        super(Teamsfranchises.TEAMSFRANCHISES);
    }

    /**
     * Create a detached, initialised TeamsfranchisesRecord
     */
    public TeamsfranchisesRecord(String franchid, String franchname, String active, String naassoc) {
        super(Teamsfranchises.TEAMSFRANCHISES);

        set(0, franchid);
        set(1, franchname);
        set(2, active);
        set(3, naassoc);
    }
}
