/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.records;


import io.corbs.baseballdb.schema.tables.Teams;
import io.corbs.baseballdb.schema.tables.interfaces.ITeams;

import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamsRecord extends TableRecordImpl<TeamsRecord> implements ITeams {

    private static final long serialVersionUID = -190412876;

    /**
     * Setter for <code>baseballdb.Teams.yearID</code>.
     */
    @Override
    public TeamsRecord setYearid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.yearID</code>.
     */
    @Override
    public Integer getYearid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>baseballdb.Teams.lgID</code>.
     */
    @Override
    public TeamsRecord setLgid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.lgID</code>.
     */
    @Override
    public String getLgid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>baseballdb.Teams.teamID</code>.
     */
    @Override
    public TeamsRecord setTeamid(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.teamID</code>.
     */
    @Override
    public String getTeamid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>baseballdb.Teams.franchID</code>.
     */
    @Override
    public TeamsRecord setFranchid(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.franchID</code>.
     */
    @Override
    public String getFranchid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>baseballdb.Teams.divID</code>.
     */
    @Override
    public TeamsRecord setDivid(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.divID</code>.
     */
    @Override
    public String getDivid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>baseballdb.Teams.Rank</code>.
     */
    @Override
    public TeamsRecord setRank(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.Rank</code>.
     */
    @Override
    public Integer getRank() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>baseballdb.Teams.G</code>.
     */
    @Override
    public TeamsRecord setG(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.G</code>.
     */
    @Override
    public Integer getG() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>baseballdb.Teams.Ghome</code>.
     */
    @Override
    public TeamsRecord setGhome(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.Ghome</code>.
     */
    @Override
    public String getGhome() {
        return (String) get(7);
    }

    /**
     * Setter for <code>baseballdb.Teams.W</code>.
     */
    @Override
    public TeamsRecord setW(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.W</code>.
     */
    @Override
    public Integer getW() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>baseballdb.Teams.L</code>.
     */
    @Override
    public TeamsRecord setL(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.L</code>.
     */
    @Override
    public Integer getL() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>baseballdb.Teams.DivWin</code>.
     */
    @Override
    public TeamsRecord setDivwin(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.DivWin</code>.
     */
    @Override
    public String getDivwin() {
        return (String) get(10);
    }

    /**
     * Setter for <code>baseballdb.Teams.WCWin</code>.
     */
    @Override
    public TeamsRecord setWcwin(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.WCWin</code>.
     */
    @Override
    public String getWcwin() {
        return (String) get(11);
    }

    /**
     * Setter for <code>baseballdb.Teams.LgWin</code>.
     */
    @Override
    public TeamsRecord setLgwin(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.LgWin</code>.
     */
    @Override
    public String getLgwin() {
        return (String) get(12);
    }

    /**
     * Setter for <code>baseballdb.Teams.WSWin</code>.
     */
    @Override
    public TeamsRecord setWswin(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.WSWin</code>.
     */
    @Override
    public String getWswin() {
        return (String) get(13);
    }

    /**
     * Setter for <code>baseballdb.Teams.R</code>.
     */
    @Override
    public TeamsRecord setR(Integer value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.R</code>.
     */
    @Override
    public Integer getR() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>baseballdb.Teams.AB</code>.
     */
    @Override
    public TeamsRecord setAb(Integer value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.AB</code>.
     */
    @Override
    public Integer getAb() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>baseballdb.Teams.H</code>.
     */
    @Override
    public TeamsRecord setH(Integer value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.H</code>.
     */
    @Override
    public Integer getH() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>baseballdb.Teams.2B</code>.
     */
    @Override
    public TeamsRecord set_2b(Integer value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.2B</code>.
     */
    @Override
    public Integer get_2b() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>baseballdb.Teams.3B</code>.
     */
    @Override
    public TeamsRecord set_3b(Integer value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.3B</code>.
     */
    @Override
    public Integer get_3b() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>baseballdb.Teams.HR</code>.
     */
    @Override
    public TeamsRecord setHr(Integer value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.HR</code>.
     */
    @Override
    public Integer getHr() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>baseballdb.Teams.BB</code>.
     */
    @Override
    public TeamsRecord setBb(Integer value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.BB</code>.
     */
    @Override
    public Integer getBb() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>baseballdb.Teams.SO</code>.
     */
    @Override
    public TeamsRecord setSo(Integer value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.SO</code>.
     */
    @Override
    public Integer getSo() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>baseballdb.Teams.SB</code>.
     */
    @Override
    public TeamsRecord setSb(Integer value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.SB</code>.
     */
    @Override
    public Integer getSb() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>baseballdb.Teams.CS</code>.
     */
    @Override
    public TeamsRecord setCs(String value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.CS</code>.
     */
    @Override
    public String getCs() {
        return (String) get(23);
    }

    /**
     * Setter for <code>baseballdb.Teams.HBP</code>.
     */
    @Override
    public TeamsRecord setHbp(String value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.HBP</code>.
     */
    @Override
    public String getHbp() {
        return (String) get(24);
    }

    /**
     * Setter for <code>baseballdb.Teams.SF</code>.
     */
    @Override
    public TeamsRecord setSf(String value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.SF</code>.
     */
    @Override
    public String getSf() {
        return (String) get(25);
    }

    /**
     * Setter for <code>baseballdb.Teams.RA</code>.
     */
    @Override
    public TeamsRecord setRa(Integer value) {
        set(26, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.RA</code>.
     */
    @Override
    public Integer getRa() {
        return (Integer) get(26);
    }

    /**
     * Setter for <code>baseballdb.Teams.ER</code>.
     */
    @Override
    public TeamsRecord setEr(Integer value) {
        set(27, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.ER</code>.
     */
    @Override
    public Integer getEr() {
        return (Integer) get(27);
    }

    /**
     * Setter for <code>baseballdb.Teams.ERA</code>.
     */
    @Override
    public TeamsRecord setEra(Double value) {
        set(28, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.ERA</code>.
     */
    @Override
    public Double getEra() {
        return (Double) get(28);
    }

    /**
     * Setter for <code>baseballdb.Teams.CG</code>.
     */
    @Override
    public TeamsRecord setCg(Integer value) {
        set(29, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.CG</code>.
     */
    @Override
    public Integer getCg() {
        return (Integer) get(29);
    }

    /**
     * Setter for <code>baseballdb.Teams.SHO</code>.
     */
    @Override
    public TeamsRecord setSho(Integer value) {
        set(30, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.SHO</code>.
     */
    @Override
    public Integer getSho() {
        return (Integer) get(30);
    }

    /**
     * Setter for <code>baseballdb.Teams.SV</code>.
     */
    @Override
    public TeamsRecord setSv(Integer value) {
        set(31, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.SV</code>.
     */
    @Override
    public Integer getSv() {
        return (Integer) get(31);
    }

    /**
     * Setter for <code>baseballdb.Teams.IPouts</code>.
     */
    @Override
    public TeamsRecord setIpouts(Integer value) {
        set(32, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.IPouts</code>.
     */
    @Override
    public Integer getIpouts() {
        return (Integer) get(32);
    }

    /**
     * Setter for <code>baseballdb.Teams.HA</code>.
     */
    @Override
    public TeamsRecord setHa(Integer value) {
        set(33, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.HA</code>.
     */
    @Override
    public Integer getHa() {
        return (Integer) get(33);
    }

    /**
     * Setter for <code>baseballdb.Teams.HRA</code>.
     */
    @Override
    public TeamsRecord setHra(Integer value) {
        set(34, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.HRA</code>.
     */
    @Override
    public Integer getHra() {
        return (Integer) get(34);
    }

    /**
     * Setter for <code>baseballdb.Teams.BBA</code>.
     */
    @Override
    public TeamsRecord setBba(Integer value) {
        set(35, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.BBA</code>.
     */
    @Override
    public Integer getBba() {
        return (Integer) get(35);
    }

    /**
     * Setter for <code>baseballdb.Teams.SOA</code>.
     */
    @Override
    public TeamsRecord setSoa(Integer value) {
        set(36, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.SOA</code>.
     */
    @Override
    public Integer getSoa() {
        return (Integer) get(36);
    }

    /**
     * Setter for <code>baseballdb.Teams.E</code>.
     */
    @Override
    public TeamsRecord setE(Integer value) {
        set(37, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.E</code>.
     */
    @Override
    public Integer getE() {
        return (Integer) get(37);
    }

    /**
     * Setter for <code>baseballdb.Teams.DP</code>.
     */
    @Override
    public TeamsRecord setDp(String value) {
        set(38, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.DP</code>.
     */
    @Override
    public String getDp() {
        return (String) get(38);
    }

    /**
     * Setter for <code>baseballdb.Teams.FP</code>.
     */
    @Override
    public TeamsRecord setFp(Double value) {
        set(39, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.FP</code>.
     */
    @Override
    public Double getFp() {
        return (Double) get(39);
    }

    /**
     * Setter for <code>baseballdb.Teams.name</code>.
     */
    @Override
    public TeamsRecord setName(String value) {
        set(40, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(40);
    }

    /**
     * Setter for <code>baseballdb.Teams.park</code>.
     */
    @Override
    public TeamsRecord setPark(String value) {
        set(41, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.park</code>.
     */
    @Override
    public String getPark() {
        return (String) get(41);
    }

    /**
     * Setter for <code>baseballdb.Teams.attendance</code>.
     */
    @Override
    public TeamsRecord setAttendance(String value) {
        set(42, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.attendance</code>.
     */
    @Override
    public String getAttendance() {
        return (String) get(42);
    }

    /**
     * Setter for <code>baseballdb.Teams.BPF</code>.
     */
    @Override
    public TeamsRecord setBpf(Integer value) {
        set(43, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.BPF</code>.
     */
    @Override
    public Integer getBpf() {
        return (Integer) get(43);
    }

    /**
     * Setter for <code>baseballdb.Teams.PPF</code>.
     */
    @Override
    public TeamsRecord setPpf(Integer value) {
        set(44, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.PPF</code>.
     */
    @Override
    public Integer getPpf() {
        return (Integer) get(44);
    }

    /**
     * Setter for <code>baseballdb.Teams.teamIDBR</code>.
     */
    @Override
    public TeamsRecord setTeamidbr(String value) {
        set(45, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.teamIDBR</code>.
     */
    @Override
    public String getTeamidbr() {
        return (String) get(45);
    }

    /**
     * Setter for <code>baseballdb.Teams.teamIDlahman45</code>.
     */
    @Override
    public TeamsRecord setTeamidlahman45(String value) {
        set(46, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.teamIDlahman45</code>.
     */
    @Override
    public String getTeamidlahman45() {
        return (String) get(46);
    }

    /**
     * Setter for <code>baseballdb.Teams.teamIDretro</code>.
     */
    @Override
    public TeamsRecord setTeamidretro(String value) {
        set(47, value);
        return this;
    }

    /**
     * Getter for <code>baseballdb.Teams.teamIDretro</code>.
     */
    @Override
    public String getTeamidretro() {
        return (String) get(47);
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITeams from) {
        setYearid(from.getYearid());
        setLgid(from.getLgid());
        setTeamid(from.getTeamid());
        setFranchid(from.getFranchid());
        setDivid(from.getDivid());
        setRank(from.getRank());
        setG(from.getG());
        setGhome(from.getGhome());
        setW(from.getW());
        setL(from.getL());
        setDivwin(from.getDivwin());
        setWcwin(from.getWcwin());
        setLgwin(from.getLgwin());
        setWswin(from.getWswin());
        setR(from.getR());
        setAb(from.getAb());
        setH(from.getH());
        set_2b(from.get_2b());
        set_3b(from.get_3b());
        setHr(from.getHr());
        setBb(from.getBb());
        setSo(from.getSo());
        setSb(from.getSb());
        setCs(from.getCs());
        setHbp(from.getHbp());
        setSf(from.getSf());
        setRa(from.getRa());
        setEr(from.getEr());
        setEra(from.getEra());
        setCg(from.getCg());
        setSho(from.getSho());
        setSv(from.getSv());
        setIpouts(from.getIpouts());
        setHa(from.getHa());
        setHra(from.getHra());
        setBba(from.getBba());
        setSoa(from.getSoa());
        setE(from.getE());
        setDp(from.getDp());
        setFp(from.getFp());
        setName(from.getName());
        setPark(from.getPark());
        setAttendance(from.getAttendance());
        setBpf(from.getBpf());
        setPpf(from.getPpf());
        setTeamidbr(from.getTeamidbr());
        setTeamidlahman45(from.getTeamidlahman45());
        setTeamidretro(from.getTeamidretro());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITeams> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamsRecord
     */
    public TeamsRecord() {
        super(Teams.TEAMS);
    }

    /**
     * Create a detached, initialised TeamsRecord
     */
    public TeamsRecord(Integer yearid, String lgid, String teamid, String franchid, String divid, Integer rank, Integer g, String ghome, Integer w, Integer l, String divwin, String wcwin, String lgwin, String wswin, Integer r, Integer ab, Integer h, Integer _2b, Integer _3b, Integer hr, Integer bb, Integer so, Integer sb, String cs, String hbp, String sf, Integer ra, Integer er, Double era, Integer cg, Integer sho, Integer sv, Integer ipouts, Integer ha, Integer hra, Integer bba, Integer soa, Integer e, String dp, Double fp, String name, String park, String attendance, Integer bpf, Integer ppf, String teamidbr, String teamidlahman45, String teamidretro) {
        super(Teams.TEAMS);

        set(0, yearid);
        set(1, lgid);
        set(2, teamid);
        set(3, franchid);
        set(4, divid);
        set(5, rank);
        set(6, g);
        set(7, ghome);
        set(8, w);
        set(9, l);
        set(10, divwin);
        set(11, wcwin);
        set(12, lgwin);
        set(13, wswin);
        set(14, r);
        set(15, ab);
        set(16, h);
        set(17, _2b);
        set(18, _3b);
        set(19, hr);
        set(20, bb);
        set(21, so);
        set(22, sb);
        set(23, cs);
        set(24, hbp);
        set(25, sf);
        set(26, ra);
        set(27, er);
        set(28, era);
        set(29, cg);
        set(30, sho);
        set(31, sv);
        set(32, ipouts);
        set(33, ha);
        set(34, hra);
        set(35, bba);
        set(36, soa);
        set(37, e);
        set(38, dp);
        set(39, fp);
        set(40, name);
        set(41, park);
        set(42, attendance);
        set(43, bpf);
        set(44, ppf);
        set(45, teamidbr);
        set(46, teamidlahman45);
        set(47, teamidretro);
    }
}
