/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.pojos;


import io.corbs.baseballdb.schema.tables.interfaces.IAppearances;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Appearances implements IAppearances {

    private static final long serialVersionUID = -1479044971;

    private Integer yearid;
    private String  teamid;
    private String  lgid;
    private String  playerid;
    private Integer gAll;
    private String  gs;
    private Integer gBatting;
    private Integer gDefense;
    private Integer gP;
    private Integer gC;
    private Integer g_1b;
    private Integer g_2b;
    private Integer g_3b;
    private Integer gSs;
    private Integer gLf;
    private Integer gCf;
    private Integer gRf;
    private Integer gOf;
    private String  gDh;
    private String  gPh;
    private String  gPr;

    public Appearances() {}

    public Appearances(Appearances value) {
        this.yearid = value.yearid;
        this.teamid = value.teamid;
        this.lgid = value.lgid;
        this.playerid = value.playerid;
        this.gAll = value.gAll;
        this.gs = value.gs;
        this.gBatting = value.gBatting;
        this.gDefense = value.gDefense;
        this.gP = value.gP;
        this.gC = value.gC;
        this.g_1b = value.g_1b;
        this.g_2b = value.g_2b;
        this.g_3b = value.g_3b;
        this.gSs = value.gSs;
        this.gLf = value.gLf;
        this.gCf = value.gCf;
        this.gRf = value.gRf;
        this.gOf = value.gOf;
        this.gDh = value.gDh;
        this.gPh = value.gPh;
        this.gPr = value.gPr;
    }

    public Appearances(
        Integer yearid,
        String  teamid,
        String  lgid,
        String  playerid,
        Integer gAll,
        String  gs,
        Integer gBatting,
        Integer gDefense,
        Integer gP,
        Integer gC,
        Integer g_1b,
        Integer g_2b,
        Integer g_3b,
        Integer gSs,
        Integer gLf,
        Integer gCf,
        Integer gRf,
        Integer gOf,
        String  gDh,
        String  gPh,
        String  gPr
    ) {
        this.yearid = yearid;
        this.teamid = teamid;
        this.lgid = lgid;
        this.playerid = playerid;
        this.gAll = gAll;
        this.gs = gs;
        this.gBatting = gBatting;
        this.gDefense = gDefense;
        this.gP = gP;
        this.gC = gC;
        this.g_1b = g_1b;
        this.g_2b = g_2b;
        this.g_3b = g_3b;
        this.gSs = gSs;
        this.gLf = gLf;
        this.gCf = gCf;
        this.gRf = gRf;
        this.gOf = gOf;
        this.gDh = gDh;
        this.gPh = gPh;
        this.gPr = gPr;
    }

    @Override
    public Integer getYearid() {
        return this.yearid;
    }

    @Override
    public Appearances setYearid(Integer yearid) {
        this.yearid = yearid;
        return this;
    }

    @Override
    public String getTeamid() {
        return this.teamid;
    }

    @Override
    public Appearances setTeamid(String teamid) {
        this.teamid = teamid;
        return this;
    }

    @Override
    public String getLgid() {
        return this.lgid;
    }

    @Override
    public Appearances setLgid(String lgid) {
        this.lgid = lgid;
        return this;
    }

    @Override
    public String getPlayerid() {
        return this.playerid;
    }

    @Override
    public Appearances setPlayerid(String playerid) {
        this.playerid = playerid;
        return this;
    }

    @Override
    public Integer getGAll() {
        return this.gAll;
    }

    @Override
    public Appearances setGAll(Integer gAll) {
        this.gAll = gAll;
        return this;
    }

    @Override
    public String getGs() {
        return this.gs;
    }

    @Override
    public Appearances setGs(String gs) {
        this.gs = gs;
        return this;
    }

    @Override
    public Integer getGBatting() {
        return this.gBatting;
    }

    @Override
    public Appearances setGBatting(Integer gBatting) {
        this.gBatting = gBatting;
        return this;
    }

    @Override
    public Integer getGDefense() {
        return this.gDefense;
    }

    @Override
    public Appearances setGDefense(Integer gDefense) {
        this.gDefense = gDefense;
        return this;
    }

    @Override
    public Integer getGP() {
        return this.gP;
    }

    @Override
    public Appearances setGP(Integer gP) {
        this.gP = gP;
        return this;
    }

    @Override
    public Integer getGC() {
        return this.gC;
    }

    @Override
    public Appearances setGC(Integer gC) {
        this.gC = gC;
        return this;
    }

    @Override
    public Integer getG_1b() {
        return this.g_1b;
    }

    @Override
    public Appearances setG_1b(Integer g_1b) {
        this.g_1b = g_1b;
        return this;
    }

    @Override
    public Integer getG_2b() {
        return this.g_2b;
    }

    @Override
    public Appearances setG_2b(Integer g_2b) {
        this.g_2b = g_2b;
        return this;
    }

    @Override
    public Integer getG_3b() {
        return this.g_3b;
    }

    @Override
    public Appearances setG_3b(Integer g_3b) {
        this.g_3b = g_3b;
        return this;
    }

    @Override
    public Integer getGSs() {
        return this.gSs;
    }

    @Override
    public Appearances setGSs(Integer gSs) {
        this.gSs = gSs;
        return this;
    }

    @Override
    public Integer getGLf() {
        return this.gLf;
    }

    @Override
    public Appearances setGLf(Integer gLf) {
        this.gLf = gLf;
        return this;
    }

    @Override
    public Integer getGCf() {
        return this.gCf;
    }

    @Override
    public Appearances setGCf(Integer gCf) {
        this.gCf = gCf;
        return this;
    }

    @Override
    public Integer getGRf() {
        return this.gRf;
    }

    @Override
    public Appearances setGRf(Integer gRf) {
        this.gRf = gRf;
        return this;
    }

    @Override
    public Integer getGOf() {
        return this.gOf;
    }

    @Override
    public Appearances setGOf(Integer gOf) {
        this.gOf = gOf;
        return this;
    }

    @Override
    public String getGDh() {
        return this.gDh;
    }

    @Override
    public Appearances setGDh(String gDh) {
        this.gDh = gDh;
        return this;
    }

    @Override
    public String getGPh() {
        return this.gPh;
    }

    @Override
    public Appearances setGPh(String gPh) {
        this.gPh = gPh;
        return this;
    }

    @Override
    public String getGPr() {
        return this.gPr;
    }

    @Override
    public Appearances setGPr(String gPr) {
        this.gPr = gPr;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Appearances (");

        sb.append(yearid);
        sb.append(", ").append(teamid);
        sb.append(", ").append(lgid);
        sb.append(", ").append(playerid);
        sb.append(", ").append(gAll);
        sb.append(", ").append(gs);
        sb.append(", ").append(gBatting);
        sb.append(", ").append(gDefense);
        sb.append(", ").append(gP);
        sb.append(", ").append(gC);
        sb.append(", ").append(g_1b);
        sb.append(", ").append(g_2b);
        sb.append(", ").append(g_3b);
        sb.append(", ").append(gSs);
        sb.append(", ").append(gLf);
        sb.append(", ").append(gCf);
        sb.append(", ").append(gRf);
        sb.append(", ").append(gOf);
        sb.append(", ").append(gDh);
        sb.append(", ").append(gPh);
        sb.append(", ").append(gPr);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IAppearances from) {
        setYearid(from.getYearid());
        setTeamid(from.getTeamid());
        setLgid(from.getLgid());
        setPlayerid(from.getPlayerid());
        setGAll(from.getGAll());
        setGs(from.getGs());
        setGBatting(from.getGBatting());
        setGDefense(from.getGDefense());
        setGP(from.getGP());
        setGC(from.getGC());
        setG_1b(from.getG_1b());
        setG_2b(from.getG_2b());
        setG_3b(from.getG_3b());
        setGSs(from.getGSs());
        setGLf(from.getGLf());
        setGCf(from.getGCf());
        setGRf(from.getGRf());
        setGOf(from.getGOf());
        setGDh(from.getGDh());
        setGPh(from.getGPh());
        setGPr(from.getGPr());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IAppearances> E into(E into) {
        into.from(this);
        return into;
    }
}
