/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.pojos;


import io.corbs.baseballdb.schema.tables.interfaces.IAwardsmanagers;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Awardsmanagers implements IAwardsmanagers {

    private static final long serialVersionUID = 2116632421;

    private String  playerid;
    private String  awardid;
    private Integer yearid;
    private String  lgid;
    private String  tie;
    private String  notes;

    public Awardsmanagers() {}

    public Awardsmanagers(Awardsmanagers value) {
        this.playerid = value.playerid;
        this.awardid = value.awardid;
        this.yearid = value.yearid;
        this.lgid = value.lgid;
        this.tie = value.tie;
        this.notes = value.notes;
    }

    public Awardsmanagers(
        String  playerid,
        String  awardid,
        Integer yearid,
        String  lgid,
        String  tie,
        String  notes
    ) {
        this.playerid = playerid;
        this.awardid = awardid;
        this.yearid = yearid;
        this.lgid = lgid;
        this.tie = tie;
        this.notes = notes;
    }

    @Override
    public String getPlayerid() {
        return this.playerid;
    }

    @Override
    public Awardsmanagers setPlayerid(String playerid) {
        this.playerid = playerid;
        return this;
    }

    @Override
    public String getAwardid() {
        return this.awardid;
    }

    @Override
    public Awardsmanagers setAwardid(String awardid) {
        this.awardid = awardid;
        return this;
    }

    @Override
    public Integer getYearid() {
        return this.yearid;
    }

    @Override
    public Awardsmanagers setYearid(Integer yearid) {
        this.yearid = yearid;
        return this;
    }

    @Override
    public String getLgid() {
        return this.lgid;
    }

    @Override
    public Awardsmanagers setLgid(String lgid) {
        this.lgid = lgid;
        return this;
    }

    @Override
    public String getTie() {
        return this.tie;
    }

    @Override
    public Awardsmanagers setTie(String tie) {
        this.tie = tie;
        return this;
    }

    @Override
    public String getNotes() {
        return this.notes;
    }

    @Override
    public Awardsmanagers setNotes(String notes) {
        this.notes = notes;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Awardsmanagers (");

        sb.append(playerid);
        sb.append(", ").append(awardid);
        sb.append(", ").append(yearid);
        sb.append(", ").append(lgid);
        sb.append(", ").append(tie);
        sb.append(", ").append(notes);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IAwardsmanagers from) {
        setPlayerid(from.getPlayerid());
        setAwardid(from.getAwardid());
        setYearid(from.getYearid());
        setLgid(from.getLgid());
        setTie(from.getTie());
        setNotes(from.getNotes());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IAwardsmanagers> E into(E into) {
        into.from(this);
        return into;
    }
}
