/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.pojos;


import io.corbs.baseballdb.schema.tables.interfaces.IFieldingofsplit;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fieldingofsplit implements IFieldingofsplit {

    private static final long serialVersionUID = -376971570;

    private String  playerid;
    private Integer yearid;
    private Integer stint;
    private String  teamid;
    private String  lgid;
    private String  pos;
    private Integer g;
    private Integer gs;
    private Integer innouts;
    private Integer po;
    private Integer a;
    private Integer e;
    private Integer dp;
    private String  pb;
    private String  wp;
    private String  sb;
    private String  cs;
    private String  zr;

    public Fieldingofsplit() {}

    public Fieldingofsplit(Fieldingofsplit value) {
        this.playerid = value.playerid;
        this.yearid = value.yearid;
        this.stint = value.stint;
        this.teamid = value.teamid;
        this.lgid = value.lgid;
        this.pos = value.pos;
        this.g = value.g;
        this.gs = value.gs;
        this.innouts = value.innouts;
        this.po = value.po;
        this.a = value.a;
        this.e = value.e;
        this.dp = value.dp;
        this.pb = value.pb;
        this.wp = value.wp;
        this.sb = value.sb;
        this.cs = value.cs;
        this.zr = value.zr;
    }

    public Fieldingofsplit(
        String  playerid,
        Integer yearid,
        Integer stint,
        String  teamid,
        String  lgid,
        String  pos,
        Integer g,
        Integer gs,
        Integer innouts,
        Integer po,
        Integer a,
        Integer e,
        Integer dp,
        String  pb,
        String  wp,
        String  sb,
        String  cs,
        String  zr
    ) {
        this.playerid = playerid;
        this.yearid = yearid;
        this.stint = stint;
        this.teamid = teamid;
        this.lgid = lgid;
        this.pos = pos;
        this.g = g;
        this.gs = gs;
        this.innouts = innouts;
        this.po = po;
        this.a = a;
        this.e = e;
        this.dp = dp;
        this.pb = pb;
        this.wp = wp;
        this.sb = sb;
        this.cs = cs;
        this.zr = zr;
    }

    @Override
    public String getPlayerid() {
        return this.playerid;
    }

    @Override
    public Fieldingofsplit setPlayerid(String playerid) {
        this.playerid = playerid;
        return this;
    }

    @Override
    public Integer getYearid() {
        return this.yearid;
    }

    @Override
    public Fieldingofsplit setYearid(Integer yearid) {
        this.yearid = yearid;
        return this;
    }

    @Override
    public Integer getStint() {
        return this.stint;
    }

    @Override
    public Fieldingofsplit setStint(Integer stint) {
        this.stint = stint;
        return this;
    }

    @Override
    public String getTeamid() {
        return this.teamid;
    }

    @Override
    public Fieldingofsplit setTeamid(String teamid) {
        this.teamid = teamid;
        return this;
    }

    @Override
    public String getLgid() {
        return this.lgid;
    }

    @Override
    public Fieldingofsplit setLgid(String lgid) {
        this.lgid = lgid;
        return this;
    }

    @Override
    public String getPos() {
        return this.pos;
    }

    @Override
    public Fieldingofsplit setPos(String pos) {
        this.pos = pos;
        return this;
    }

    @Override
    public Integer getG() {
        return this.g;
    }

    @Override
    public Fieldingofsplit setG(Integer g) {
        this.g = g;
        return this;
    }

    @Override
    public Integer getGs() {
        return this.gs;
    }

    @Override
    public Fieldingofsplit setGs(Integer gs) {
        this.gs = gs;
        return this;
    }

    @Override
    public Integer getInnouts() {
        return this.innouts;
    }

    @Override
    public Fieldingofsplit setInnouts(Integer innouts) {
        this.innouts = innouts;
        return this;
    }

    @Override
    public Integer getPo() {
        return this.po;
    }

    @Override
    public Fieldingofsplit setPo(Integer po) {
        this.po = po;
        return this;
    }

    @Override
    public Integer getA() {
        return this.a;
    }

    @Override
    public Fieldingofsplit setA(Integer a) {
        this.a = a;
        return this;
    }

    @Override
    public Integer getE() {
        return this.e;
    }

    @Override
    public Fieldingofsplit setE(Integer e) {
        this.e = e;
        return this;
    }

    @Override
    public Integer getDp() {
        return this.dp;
    }

    @Override
    public Fieldingofsplit setDp(Integer dp) {
        this.dp = dp;
        return this;
    }

    @Override
    public String getPb() {
        return this.pb;
    }

    @Override
    public Fieldingofsplit setPb(String pb) {
        this.pb = pb;
        return this;
    }

    @Override
    public String getWp() {
        return this.wp;
    }

    @Override
    public Fieldingofsplit setWp(String wp) {
        this.wp = wp;
        return this;
    }

    @Override
    public String getSb() {
        return this.sb;
    }

    @Override
    public Fieldingofsplit setSb(String sb) {
        this.sb = sb;
        return this;
    }

    @Override
    public String getCs() {
        return this.cs;
    }

    @Override
    public Fieldingofsplit setCs(String cs) {
        this.cs = cs;
        return this;
    }

    @Override
    public String getZr() {
        return this.zr;
    }

    @Override
    public Fieldingofsplit setZr(String zr) {
        this.zr = zr;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Fieldingofsplit (");

        sb.append(playerid);
        sb.append(", ").append(yearid);
        sb.append(", ").append(stint);
        sb.append(", ").append(teamid);
        sb.append(", ").append(lgid);
        sb.append(", ").append(pos);
        sb.append(", ").append(g);
        sb.append(", ").append(gs);
        sb.append(", ").append(innouts);
        sb.append(", ").append(po);
        sb.append(", ").append(a);
        sb.append(", ").append(e);
        sb.append(", ").append(dp);
        sb.append(", ").append(pb);
        sb.append(", ").append(wp);
        sb.append(", ").append(sb);
        sb.append(", ").append(cs);
        sb.append(", ").append(zr);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IFieldingofsplit from) {
        setPlayerid(from.getPlayerid());
        setYearid(from.getYearid());
        setStint(from.getStint());
        setTeamid(from.getTeamid());
        setLgid(from.getLgid());
        setPos(from.getPos());
        setG(from.getG());
        setGs(from.getGs());
        setInnouts(from.getInnouts());
        setPo(from.getPo());
        setA(from.getA());
        setE(from.getE());
        setDp(from.getDp());
        setPb(from.getPb());
        setWp(from.getWp());
        setSb(from.getSb());
        setCs(from.getCs());
        setZr(from.getZr());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IFieldingofsplit> E into(E into) {
        into.from(this);
        return into;
    }
}
