/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.pojos;


import io.corbs.baseballdb.schema.tables.interfaces.IFieldingof;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fieldingof implements IFieldingof {

    private static final long serialVersionUID = 718306168;

    private String  playerid;
    private Integer yearid;
    private Integer stint;
    private Integer glf;
    private Integer gcf;
    private Integer grf;

    public Fieldingof() {}

    public Fieldingof(Fieldingof value) {
        this.playerid = value.playerid;
        this.yearid = value.yearid;
        this.stint = value.stint;
        this.glf = value.glf;
        this.gcf = value.gcf;
        this.grf = value.grf;
    }

    public Fieldingof(
        String  playerid,
        Integer yearid,
        Integer stint,
        Integer glf,
        Integer gcf,
        Integer grf
    ) {
        this.playerid = playerid;
        this.yearid = yearid;
        this.stint = stint;
        this.glf = glf;
        this.gcf = gcf;
        this.grf = grf;
    }

    @Override
    public String getPlayerid() {
        return this.playerid;
    }

    @Override
    public Fieldingof setPlayerid(String playerid) {
        this.playerid = playerid;
        return this;
    }

    @Override
    public Integer getYearid() {
        return this.yearid;
    }

    @Override
    public Fieldingof setYearid(Integer yearid) {
        this.yearid = yearid;
        return this;
    }

    @Override
    public Integer getStint() {
        return this.stint;
    }

    @Override
    public Fieldingof setStint(Integer stint) {
        this.stint = stint;
        return this;
    }

    @Override
    public Integer getGlf() {
        return this.glf;
    }

    @Override
    public Fieldingof setGlf(Integer glf) {
        this.glf = glf;
        return this;
    }

    @Override
    public Integer getGcf() {
        return this.gcf;
    }

    @Override
    public Fieldingof setGcf(Integer gcf) {
        this.gcf = gcf;
        return this;
    }

    @Override
    public Integer getGrf() {
        return this.grf;
    }

    @Override
    public Fieldingof setGrf(Integer grf) {
        this.grf = grf;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Fieldingof (");

        sb.append(playerid);
        sb.append(", ").append(yearid);
        sb.append(", ").append(stint);
        sb.append(", ").append(glf);
        sb.append(", ").append(gcf);
        sb.append(", ").append(grf);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IFieldingof from) {
        setPlayerid(from.getPlayerid());
        setYearid(from.getYearid());
        setStint(from.getStint());
        setGlf(from.getGlf());
        setGcf(from.getGcf());
        setGrf(from.getGrf());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IFieldingof> E into(E into) {
        into.from(this);
        return into;
    }
}
