/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.pojos;


import io.corbs.baseballdb.schema.tables.interfaces.IFieldingpost;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fieldingpost implements IFieldingpost {

    private static final long serialVersionUID = -535808973;

    private String  playerid;
    private Integer yearid;
    private String  teamid;
    private String  lgid;
    private String  round;
    private String  pos;
    private Integer g;
    private Integer gs;
    private Integer innouts;
    private Integer po;
    private Integer a;
    private Integer e;
    private Integer dp;
    private Integer tp;
    private String  pb;
    private String  sb;
    private String  cs;

    public Fieldingpost() {}

    public Fieldingpost(Fieldingpost value) {
        this.playerid = value.playerid;
        this.yearid = value.yearid;
        this.teamid = value.teamid;
        this.lgid = value.lgid;
        this.round = value.round;
        this.pos = value.pos;
        this.g = value.g;
        this.gs = value.gs;
        this.innouts = value.innouts;
        this.po = value.po;
        this.a = value.a;
        this.e = value.e;
        this.dp = value.dp;
        this.tp = value.tp;
        this.pb = value.pb;
        this.sb = value.sb;
        this.cs = value.cs;
    }

    public Fieldingpost(
        String  playerid,
        Integer yearid,
        String  teamid,
        String  lgid,
        String  round,
        String  pos,
        Integer g,
        Integer gs,
        Integer innouts,
        Integer po,
        Integer a,
        Integer e,
        Integer dp,
        Integer tp,
        String  pb,
        String  sb,
        String  cs
    ) {
        this.playerid = playerid;
        this.yearid = yearid;
        this.teamid = teamid;
        this.lgid = lgid;
        this.round = round;
        this.pos = pos;
        this.g = g;
        this.gs = gs;
        this.innouts = innouts;
        this.po = po;
        this.a = a;
        this.e = e;
        this.dp = dp;
        this.tp = tp;
        this.pb = pb;
        this.sb = sb;
        this.cs = cs;
    }

    @Override
    public String getPlayerid() {
        return this.playerid;
    }

    @Override
    public Fieldingpost setPlayerid(String playerid) {
        this.playerid = playerid;
        return this;
    }

    @Override
    public Integer getYearid() {
        return this.yearid;
    }

    @Override
    public Fieldingpost setYearid(Integer yearid) {
        this.yearid = yearid;
        return this;
    }

    @Override
    public String getTeamid() {
        return this.teamid;
    }

    @Override
    public Fieldingpost setTeamid(String teamid) {
        this.teamid = teamid;
        return this;
    }

    @Override
    public String getLgid() {
        return this.lgid;
    }

    @Override
    public Fieldingpost setLgid(String lgid) {
        this.lgid = lgid;
        return this;
    }

    @Override
    public String getRound() {
        return this.round;
    }

    @Override
    public Fieldingpost setRound(String round) {
        this.round = round;
        return this;
    }

    @Override
    public String getPos() {
        return this.pos;
    }

    @Override
    public Fieldingpost setPos(String pos) {
        this.pos = pos;
        return this;
    }

    @Override
    public Integer getG() {
        return this.g;
    }

    @Override
    public Fieldingpost setG(Integer g) {
        this.g = g;
        return this;
    }

    @Override
    public Integer getGs() {
        return this.gs;
    }

    @Override
    public Fieldingpost setGs(Integer gs) {
        this.gs = gs;
        return this;
    }

    @Override
    public Integer getInnouts() {
        return this.innouts;
    }

    @Override
    public Fieldingpost setInnouts(Integer innouts) {
        this.innouts = innouts;
        return this;
    }

    @Override
    public Integer getPo() {
        return this.po;
    }

    @Override
    public Fieldingpost setPo(Integer po) {
        this.po = po;
        return this;
    }

    @Override
    public Integer getA() {
        return this.a;
    }

    @Override
    public Fieldingpost setA(Integer a) {
        this.a = a;
        return this;
    }

    @Override
    public Integer getE() {
        return this.e;
    }

    @Override
    public Fieldingpost setE(Integer e) {
        this.e = e;
        return this;
    }

    @Override
    public Integer getDp() {
        return this.dp;
    }

    @Override
    public Fieldingpost setDp(Integer dp) {
        this.dp = dp;
        return this;
    }

    @Override
    public Integer getTp() {
        return this.tp;
    }

    @Override
    public Fieldingpost setTp(Integer tp) {
        this.tp = tp;
        return this;
    }

    @Override
    public String getPb() {
        return this.pb;
    }

    @Override
    public Fieldingpost setPb(String pb) {
        this.pb = pb;
        return this;
    }

    @Override
    public String getSb() {
        return this.sb;
    }

    @Override
    public Fieldingpost setSb(String sb) {
        this.sb = sb;
        return this;
    }

    @Override
    public String getCs() {
        return this.cs;
    }

    @Override
    public Fieldingpost setCs(String cs) {
        this.cs = cs;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Fieldingpost (");

        sb.append(playerid);
        sb.append(", ").append(yearid);
        sb.append(", ").append(teamid);
        sb.append(", ").append(lgid);
        sb.append(", ").append(round);
        sb.append(", ").append(pos);
        sb.append(", ").append(g);
        sb.append(", ").append(gs);
        sb.append(", ").append(innouts);
        sb.append(", ").append(po);
        sb.append(", ").append(a);
        sb.append(", ").append(e);
        sb.append(", ").append(dp);
        sb.append(", ").append(tp);
        sb.append(", ").append(pb);
        sb.append(", ").append(sb);
        sb.append(", ").append(cs);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IFieldingpost from) {
        setPlayerid(from.getPlayerid());
        setYearid(from.getYearid());
        setTeamid(from.getTeamid());
        setLgid(from.getLgid());
        setRound(from.getRound());
        setPos(from.getPos());
        setG(from.getG());
        setGs(from.getGs());
        setInnouts(from.getInnouts());
        setPo(from.getPo());
        setA(from.getA());
        setE(from.getE());
        setDp(from.getDp());
        setTp(from.getTp());
        setPb(from.getPb());
        setSb(from.getSb());
        setCs(from.getCs());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IFieldingpost> E into(E into) {
        into.from(this);
        return into;
    }
}
