/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.pojos;


import io.corbs.baseballdb.schema.tables.interfaces.IManagershalf;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Managershalf implements IManagershalf {

    private static final long serialVersionUID = -1574208439;

    private String  playerid;
    private Integer yearid;
    private String  teamid;
    private String  lgid;
    private Integer inseason;
    private Integer half;
    private Integer g;
    private Integer w;
    private Integer l;
    private Integer rank;

    public Managershalf() {}

    public Managershalf(Managershalf value) {
        this.playerid = value.playerid;
        this.yearid = value.yearid;
        this.teamid = value.teamid;
        this.lgid = value.lgid;
        this.inseason = value.inseason;
        this.half = value.half;
        this.g = value.g;
        this.w = value.w;
        this.l = value.l;
        this.rank = value.rank;
    }

    public Managershalf(
        String  playerid,
        Integer yearid,
        String  teamid,
        String  lgid,
        Integer inseason,
        Integer half,
        Integer g,
        Integer w,
        Integer l,
        Integer rank
    ) {
        this.playerid = playerid;
        this.yearid = yearid;
        this.teamid = teamid;
        this.lgid = lgid;
        this.inseason = inseason;
        this.half = half;
        this.g = g;
        this.w = w;
        this.l = l;
        this.rank = rank;
    }

    @Override
    public String getPlayerid() {
        return this.playerid;
    }

    @Override
    public Managershalf setPlayerid(String playerid) {
        this.playerid = playerid;
        return this;
    }

    @Override
    public Integer getYearid() {
        return this.yearid;
    }

    @Override
    public Managershalf setYearid(Integer yearid) {
        this.yearid = yearid;
        return this;
    }

    @Override
    public String getTeamid() {
        return this.teamid;
    }

    @Override
    public Managershalf setTeamid(String teamid) {
        this.teamid = teamid;
        return this;
    }

    @Override
    public String getLgid() {
        return this.lgid;
    }

    @Override
    public Managershalf setLgid(String lgid) {
        this.lgid = lgid;
        return this;
    }

    @Override
    public Integer getInseason() {
        return this.inseason;
    }

    @Override
    public Managershalf setInseason(Integer inseason) {
        this.inseason = inseason;
        return this;
    }

    @Override
    public Integer getHalf() {
        return this.half;
    }

    @Override
    public Managershalf setHalf(Integer half) {
        this.half = half;
        return this;
    }

    @Override
    public Integer getG() {
        return this.g;
    }

    @Override
    public Managershalf setG(Integer g) {
        this.g = g;
        return this;
    }

    @Override
    public Integer getW() {
        return this.w;
    }

    @Override
    public Managershalf setW(Integer w) {
        this.w = w;
        return this;
    }

    @Override
    public Integer getL() {
        return this.l;
    }

    @Override
    public Managershalf setL(Integer l) {
        this.l = l;
        return this;
    }

    @Override
    public Integer getRank() {
        return this.rank;
    }

    @Override
    public Managershalf setRank(Integer rank) {
        this.rank = rank;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Managershalf (");

        sb.append(playerid);
        sb.append(", ").append(yearid);
        sb.append(", ").append(teamid);
        sb.append(", ").append(lgid);
        sb.append(", ").append(inseason);
        sb.append(", ").append(half);
        sb.append(", ").append(g);
        sb.append(", ").append(w);
        sb.append(", ").append(l);
        sb.append(", ").append(rank);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IManagershalf from) {
        setPlayerid(from.getPlayerid());
        setYearid(from.getYearid());
        setTeamid(from.getTeamid());
        setLgid(from.getLgid());
        setInseason(from.getInseason());
        setHalf(from.getHalf());
        setG(from.getG());
        setW(from.getW());
        setL(from.getL());
        setRank(from.getRank());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IManagershalf> E into(E into) {
        into.from(this);
        return into;
    }
}
