/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.pojos;


import io.corbs.baseballdb.schema.tables.interfaces.IPitching;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pitching implements IPitching {

    private static final long serialVersionUID = -1761811354;

    private String  playerid;
    private Integer yearid;
    private Integer stint;
    private String  teamid;
    private String  lgid;
    private Integer w;
    private Integer l;
    private Integer g;
    private Integer gs;
    private Integer cg;
    private Integer sho;
    private Integer sv;
    private Integer ipouts;
    private Integer h;
    private Integer er;
    private Integer hr;
    private Integer bb;
    private Integer so;
    private String  baopp;
    private Double  era;
    private String  ibb;
    private String  wp;
    private String  hbp;
    private Integer bk;
    private String  bfp;
    private String  gf;
    private Integer r;
    private String  sh;
    private String  sf;
    private String  gidp;

    public Pitching() {}

    public Pitching(Pitching value) {
        this.playerid = value.playerid;
        this.yearid = value.yearid;
        this.stint = value.stint;
        this.teamid = value.teamid;
        this.lgid = value.lgid;
        this.w = value.w;
        this.l = value.l;
        this.g = value.g;
        this.gs = value.gs;
        this.cg = value.cg;
        this.sho = value.sho;
        this.sv = value.sv;
        this.ipouts = value.ipouts;
        this.h = value.h;
        this.er = value.er;
        this.hr = value.hr;
        this.bb = value.bb;
        this.so = value.so;
        this.baopp = value.baopp;
        this.era = value.era;
        this.ibb = value.ibb;
        this.wp = value.wp;
        this.hbp = value.hbp;
        this.bk = value.bk;
        this.bfp = value.bfp;
        this.gf = value.gf;
        this.r = value.r;
        this.sh = value.sh;
        this.sf = value.sf;
        this.gidp = value.gidp;
    }

    public Pitching(
        String  playerid,
        Integer yearid,
        Integer stint,
        String  teamid,
        String  lgid,
        Integer w,
        Integer l,
        Integer g,
        Integer gs,
        Integer cg,
        Integer sho,
        Integer sv,
        Integer ipouts,
        Integer h,
        Integer er,
        Integer hr,
        Integer bb,
        Integer so,
        String  baopp,
        Double  era,
        String  ibb,
        String  wp,
        String  hbp,
        Integer bk,
        String  bfp,
        String  gf,
        Integer r,
        String  sh,
        String  sf,
        String  gidp
    ) {
        this.playerid = playerid;
        this.yearid = yearid;
        this.stint = stint;
        this.teamid = teamid;
        this.lgid = lgid;
        this.w = w;
        this.l = l;
        this.g = g;
        this.gs = gs;
        this.cg = cg;
        this.sho = sho;
        this.sv = sv;
        this.ipouts = ipouts;
        this.h = h;
        this.er = er;
        this.hr = hr;
        this.bb = bb;
        this.so = so;
        this.baopp = baopp;
        this.era = era;
        this.ibb = ibb;
        this.wp = wp;
        this.hbp = hbp;
        this.bk = bk;
        this.bfp = bfp;
        this.gf = gf;
        this.r = r;
        this.sh = sh;
        this.sf = sf;
        this.gidp = gidp;
    }

    @Override
    public String getPlayerid() {
        return this.playerid;
    }

    @Override
    public Pitching setPlayerid(String playerid) {
        this.playerid = playerid;
        return this;
    }

    @Override
    public Integer getYearid() {
        return this.yearid;
    }

    @Override
    public Pitching setYearid(Integer yearid) {
        this.yearid = yearid;
        return this;
    }

    @Override
    public Integer getStint() {
        return this.stint;
    }

    @Override
    public Pitching setStint(Integer stint) {
        this.stint = stint;
        return this;
    }

    @Override
    public String getTeamid() {
        return this.teamid;
    }

    @Override
    public Pitching setTeamid(String teamid) {
        this.teamid = teamid;
        return this;
    }

    @Override
    public String getLgid() {
        return this.lgid;
    }

    @Override
    public Pitching setLgid(String lgid) {
        this.lgid = lgid;
        return this;
    }

    @Override
    public Integer getW() {
        return this.w;
    }

    @Override
    public Pitching setW(Integer w) {
        this.w = w;
        return this;
    }

    @Override
    public Integer getL() {
        return this.l;
    }

    @Override
    public Pitching setL(Integer l) {
        this.l = l;
        return this;
    }

    @Override
    public Integer getG() {
        return this.g;
    }

    @Override
    public Pitching setG(Integer g) {
        this.g = g;
        return this;
    }

    @Override
    public Integer getGs() {
        return this.gs;
    }

    @Override
    public Pitching setGs(Integer gs) {
        this.gs = gs;
        return this;
    }

    @Override
    public Integer getCg() {
        return this.cg;
    }

    @Override
    public Pitching setCg(Integer cg) {
        this.cg = cg;
        return this;
    }

    @Override
    public Integer getSho() {
        return this.sho;
    }

    @Override
    public Pitching setSho(Integer sho) {
        this.sho = sho;
        return this;
    }

    @Override
    public Integer getSv() {
        return this.sv;
    }

    @Override
    public Pitching setSv(Integer sv) {
        this.sv = sv;
        return this;
    }

    @Override
    public Integer getIpouts() {
        return this.ipouts;
    }

    @Override
    public Pitching setIpouts(Integer ipouts) {
        this.ipouts = ipouts;
        return this;
    }

    @Override
    public Integer getH() {
        return this.h;
    }

    @Override
    public Pitching setH(Integer h) {
        this.h = h;
        return this;
    }

    @Override
    public Integer getEr() {
        return this.er;
    }

    @Override
    public Pitching setEr(Integer er) {
        this.er = er;
        return this;
    }

    @Override
    public Integer getHr() {
        return this.hr;
    }

    @Override
    public Pitching setHr(Integer hr) {
        this.hr = hr;
        return this;
    }

    @Override
    public Integer getBb() {
        return this.bb;
    }

    @Override
    public Pitching setBb(Integer bb) {
        this.bb = bb;
        return this;
    }

    @Override
    public Integer getSo() {
        return this.so;
    }

    @Override
    public Pitching setSo(Integer so) {
        this.so = so;
        return this;
    }

    @Override
    public String getBaopp() {
        return this.baopp;
    }

    @Override
    public Pitching setBaopp(String baopp) {
        this.baopp = baopp;
        return this;
    }

    @Override
    public Double getEra() {
        return this.era;
    }

    @Override
    public Pitching setEra(Double era) {
        this.era = era;
        return this;
    }

    @Override
    public String getIbb() {
        return this.ibb;
    }

    @Override
    public Pitching setIbb(String ibb) {
        this.ibb = ibb;
        return this;
    }

    @Override
    public String getWp() {
        return this.wp;
    }

    @Override
    public Pitching setWp(String wp) {
        this.wp = wp;
        return this;
    }

    @Override
    public String getHbp() {
        return this.hbp;
    }

    @Override
    public Pitching setHbp(String hbp) {
        this.hbp = hbp;
        return this;
    }

    @Override
    public Integer getBk() {
        return this.bk;
    }

    @Override
    public Pitching setBk(Integer bk) {
        this.bk = bk;
        return this;
    }

    @Override
    public String getBfp() {
        return this.bfp;
    }

    @Override
    public Pitching setBfp(String bfp) {
        this.bfp = bfp;
        return this;
    }

    @Override
    public String getGf() {
        return this.gf;
    }

    @Override
    public Pitching setGf(String gf) {
        this.gf = gf;
        return this;
    }

    @Override
    public Integer getR() {
        return this.r;
    }

    @Override
    public Pitching setR(Integer r) {
        this.r = r;
        return this;
    }

    @Override
    public String getSh() {
        return this.sh;
    }

    @Override
    public Pitching setSh(String sh) {
        this.sh = sh;
        return this;
    }

    @Override
    public String getSf() {
        return this.sf;
    }

    @Override
    public Pitching setSf(String sf) {
        this.sf = sf;
        return this;
    }

    @Override
    public String getGidp() {
        return this.gidp;
    }

    @Override
    public Pitching setGidp(String gidp) {
        this.gidp = gidp;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Pitching (");

        sb.append(playerid);
        sb.append(", ").append(yearid);
        sb.append(", ").append(stint);
        sb.append(", ").append(teamid);
        sb.append(", ").append(lgid);
        sb.append(", ").append(w);
        sb.append(", ").append(l);
        sb.append(", ").append(g);
        sb.append(", ").append(gs);
        sb.append(", ").append(cg);
        sb.append(", ").append(sho);
        sb.append(", ").append(sv);
        sb.append(", ").append(ipouts);
        sb.append(", ").append(h);
        sb.append(", ").append(er);
        sb.append(", ").append(hr);
        sb.append(", ").append(bb);
        sb.append(", ").append(so);
        sb.append(", ").append(baopp);
        sb.append(", ").append(era);
        sb.append(", ").append(ibb);
        sb.append(", ").append(wp);
        sb.append(", ").append(hbp);
        sb.append(", ").append(bk);
        sb.append(", ").append(bfp);
        sb.append(", ").append(gf);
        sb.append(", ").append(r);
        sb.append(", ").append(sh);
        sb.append(", ").append(sf);
        sb.append(", ").append(gidp);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IPitching from) {
        setPlayerid(from.getPlayerid());
        setYearid(from.getYearid());
        setStint(from.getStint());
        setTeamid(from.getTeamid());
        setLgid(from.getLgid());
        setW(from.getW());
        setL(from.getL());
        setG(from.getG());
        setGs(from.getGs());
        setCg(from.getCg());
        setSho(from.getSho());
        setSv(from.getSv());
        setIpouts(from.getIpouts());
        setH(from.getH());
        setEr(from.getEr());
        setHr(from.getHr());
        setBb(from.getBb());
        setSo(from.getSo());
        setBaopp(from.getBaopp());
        setEra(from.getEra());
        setIbb(from.getIbb());
        setWp(from.getWp());
        setHbp(from.getHbp());
        setBk(from.getBk());
        setBfp(from.getBfp());
        setGf(from.getGf());
        setR(from.getR());
        setSh(from.getSh());
        setSf(from.getSf());
        setGidp(from.getGidp());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IPitching> E into(E into) {
        into.from(this);
        return into;
    }
}
