/*
 * This file is generated by jOOQ.
*/
package io.corbs.baseballdb.schema.tables.pojos;


import io.corbs.baseballdb.schema.tables.interfaces.ISalaries;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Salaries implements ISalaries {

    private static final long serialVersionUID = 1336468006;

    private Integer yearid;
    private String  teamid;
    private String  lgid;
    private String  playerid;
    private Integer salary;

    public Salaries() {}

    public Salaries(Salaries value) {
        this.yearid = value.yearid;
        this.teamid = value.teamid;
        this.lgid = value.lgid;
        this.playerid = value.playerid;
        this.salary = value.salary;
    }

    public Salaries(
        Integer yearid,
        String  teamid,
        String  lgid,
        String  playerid,
        Integer salary
    ) {
        this.yearid = yearid;
        this.teamid = teamid;
        this.lgid = lgid;
        this.playerid = playerid;
        this.salary = salary;
    }

    @Override
    public Integer getYearid() {
        return this.yearid;
    }

    @Override
    public Salaries setYearid(Integer yearid) {
        this.yearid = yearid;
        return this;
    }

    @Override
    public String getTeamid() {
        return this.teamid;
    }

    @Override
    public Salaries setTeamid(String teamid) {
        this.teamid = teamid;
        return this;
    }

    @Override
    public String getLgid() {
        return this.lgid;
    }

    @Override
    public Salaries setLgid(String lgid) {
        this.lgid = lgid;
        return this;
    }

    @Override
    public String getPlayerid() {
        return this.playerid;
    }

    @Override
    public Salaries setPlayerid(String playerid) {
        this.playerid = playerid;
        return this;
    }

    @Override
    public Integer getSalary() {
        return this.salary;
    }

    @Override
    public Salaries setSalary(Integer salary) {
        this.salary = salary;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Salaries (");

        sb.append(yearid);
        sb.append(", ").append(teamid);
        sb.append(", ").append(lgid);
        sb.append(", ").append(playerid);
        sb.append(", ").append(salary);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ISalaries from) {
        setYearid(from.getYearid());
        setTeamid(from.getTeamid());
        setLgid(from.getLgid());
        setPlayerid(from.getPlayerid());
        setSalary(from.getSalary());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ISalaries> E into(E into) {
        into.from(this);
        return into;
    }
}
